-- Drop added columns
ALTER TABLE SMP_CREDENTIAL DROP COLUMN IF EXISTS RESET_EXPIRE_ON;
ALTER TABLE SMP_CREDENTIAL DROP COLUMN IF EXISTS RESET_TOKEN;

ALTER TABLE SMP_CREDENTIAL_AUD DROP COLUMN IF EXISTS RESET_EXPIRE_ON;
ALTER TABLE SMP_CREDENTIAL_AUD DROP COLUMN IF EXISTS RESET_TOKEN;

ALTER TABLE SMP_DOCUMENT DROP COLUMN IF EXISTS REF_DOCUMENT_URL;
ALTER TABLE SMP_DOCUMENT DROP COLUMN IF EXISTS SHARING_ENABLED;
ALTER TABLE SMP_DOCUMENT DROP COLUMN IF EXISTS FK_REF_DOCUMENT_ID;

ALTER TABLE SMP_DOCUMENT_AUD DROP COLUMN IF EXISTS REF_DOCUMENT_URL;
ALTER TABLE SMP_DOCUMENT_AUD DROP COLUMN IF EXISTS SHARING_ENABLED;
ALTER TABLE SMP_DOCUMENT_AUD DROP COLUMN IF EXISTS FK_REF_DOCUMENT_ID;

ALTER TABLE SMP_DOCUMENT_VERSION DROP COLUMN IF EXISTS STATUS;
ALTER TABLE SMP_DOCUMENT_VERSION_AUD DROP COLUMN IF EXISTS STATUS;

ALTER TABLE SMP_RESOURCE DROP COLUMN IF EXISTS REVIEW_ENABLED;
ALTER TABLE SMP_RESOURCE_AUD DROP COLUMN IF EXISTS REVIEW_ENABLED;

ALTER TABLE SMP_RESOURCE_MEMBER DROP COLUMN IF EXISTS PERMISSION_REVIEW;
ALTER TABLE SMP_RESOURCE_MEMBER_AUD DROP COLUMN IF EXISTS PERMISSION_REVIEW;

-- Drop created tables
DROP TABLE IF EXISTS SMP_DOCUMENT_PROPERTY;
DROP TABLE IF EXISTS SMP_DOCUMENT_PROPERTY_AUD;
DROP TABLE IF EXISTS SMP_DOCUMENT_VERSION_EVENT;
DROP TABLE IF EXISTS SMP_DOMAIN_CONFIGURATION;
DROP TABLE IF EXISTS SMP_DOMAIN_CONFIGURATION_AUD;

-- Drop created indexes
DROP INDEX IF EXISTS SMP_DOCVEREVNT_DOCVER_IDX ON SMP_DOCUMENT_VERSION_EVENT;

-- Drop added constraints
ALTER TABLE SMP_DOCUMENT_PROPERTY DROP CONSTRAINT IF EXISTS SMP_DOC_PROP_IDX;
ALTER TABLE SMP_DOMAIN_CONFIGURATION DROP CONSTRAINT IF EXISTS SMP_DOMAIN_CONF_IDX;

ALTER TABLE SMP_DOCUMENT DROP CONSTRAINT IF EXISTS FKbytp2kp8g3pj8qfp1g6a2g7p;
ALTER TABLE SMP_DOCUMENT_PROPERTY DROP CONSTRAINT IF EXISTS FKfag3795e9mrvfvesd00yis9yh;
ALTER TABLE SMP_DOCUMENT_PROPERTY_AUD DROP CONSTRAINT IF EXISTS FK81057kcrugb1cfm0io5vkxtin;
ALTER TABLE SMP_DOCUMENT_VERSION_EVENT DROP CONSTRAINT IF EXISTS FK6es2svpoxyrnt1h05c9junmdn;
ALTER TABLE SMP_DOMAIN_CONFIGURATION DROP CONSTRAINT IF EXISTS FK4303vstoigqtmeo3t2i034gm3;
ALTER TABLE SMP_DOMAIN_CONFIGURATION_AUD DROP CONSTRAINT IF EXISTS FKkelcga805bleh5x256hy5e1xb;
