
-- drop the added indexes
ALTER TABLE SMP_DOCUMENT DROP CONSTRAINT  FKbytp2kp8g3pj8qfp1g6a2g7p;
ALTER TABLE SMP_DOCUMENT_PROPERTY DROP CONSTRAINT  FKfag3795e9mrvfvesd00yis9yh;
ALTER TABLE SMP_DOCUMENT_PROPERTY_AUD DROP CONSTRAINT  FK81057kcrugb1cfm0io5vkxtin;
ALTER TABLE SMP_DOCUMENT_VERSION_EVENT DROP CONSTRAINT FK6es2svpoxyrnt1h05c9junmdn;
ALTER TABLE SMP_DOMAIN_CONFIGURATION DROP CONSTRAINT FK4303vstoigqtmeo3t2i034gm3;
ALTER TABLE SMP_DOMAIN_CONFIGURATION_AUD DROP CONSTRAINT FKkelcga805bleh5x256hy5e1xb;

-- Drop added columns
ALTER TABLE SMP_CREDENTIAL DROP COLUMN RESET_EXPIRE_ON;
ALTER TABLE SMP_CREDENTIAL DROP COLUMN RESET_TOKEN;

ALTER TABLE SMP_CREDENTIAL_AUD DROP COLUMN RESET_EXPIRE_ON;
ALTER TABLE SMP_CREDENTIAL_AUD DROP COLUMN RESET_TOKEN;

ALTER TABLE SMP_DOCUMENT DROP COLUMN REF_DOCUMENT_URL;
ALTER TABLE SMP_DOCUMENT DROP COLUMN SHARING_ENABLED;
ALTER TABLE SMP_DOCUMENT DROP COLUMN FK_REF_DOCUMENT_ID;

ALTER TABLE SMP_DOCUMENT_AUD DROP COLUMN REF_DOCUMENT_URL;
ALTER TABLE SMP_DOCUMENT_AUD DROP COLUMN SHARING_ENABLED;
ALTER TABLE SMP_DOCUMENT_AUD DROP COLUMN FK_REF_DOCUMENT_ID;

ALTER TABLE SMP_DOCUMENT_VERSION DROP COLUMN STATUS;
ALTER TABLE SMP_DOCUMENT_VERSION_AUD DROP COLUMN STATUS;

ALTER TABLE SMP_RESOURCE DROP COLUMN REVIEW_ENABLED;
ALTER TABLE SMP_RESOURCE_AUD DROP COLUMN REVIEW_ENABLED;

ALTER TABLE SMP_RESOURCE_MEMBER DROP COLUMN PERMISSION_REVIEW;
ALTER TABLE SMP_RESOURCE_MEMBER_AUD DROP COLUMN PERMISSION_REVIEW;

-- Drop created tables
DROP TABLE IF EXISTS SMP_DOCUMENT_PROPERTY;
DROP TABLE IF EXISTS SMP_DOCUMENT_PROPERTY_AUD;
DROP TABLE IF EXISTS SMP_DOCUMENT_VERSION_EVENT;
DROP TABLE IF EXISTS SMP_DOMAIN_CONFIGURATION;
DROP TABLE IF EXISTS SMP_DOMAIN_CONFIGURATION_AUD;

