package backend.ecodex.org._1_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-03-06T09:46:21.691+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://org.ecodex.backend/1_1/", name = "BackendInterface")
@XmlSeeAlso({ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class, org.w3._2003._05.soap_envelope.ObjectFactory.class, org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BackendInterface {

    @WebResult(name = "sendResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "sendResponse")
    @WebMethod
    public SendResponse sendMessageWithReference(
        @WebParam(partName = "sendRequestURL", name = "sendRequestURL", targetNamespace = "http://org.ecodex.backend/1_1/")
        SendRequestURL sendRequestURL,
        @WebParam(partName = "ebMSHeaderInfo", name = "Messaging", targetNamespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", header = true)
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging ebMSHeaderInfo
    ) throws SendMessageWithReferenceFault;

    @WebResult(name = "sendResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "sendResponse")
    @WebMethod
    public SendResponse sendMessage(
        @WebParam(partName = "sendRequest", name = "sendRequest", targetNamespace = "http://org.ecodex.backend/1_1/")
        SendRequest sendRequest,
        @WebParam(partName = "ebMSHeaderInfo", name = "Messaging", targetNamespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", header = true)
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging ebMSHeaderInfo
    ) throws SendMessageFault;

    @WebResult(name = "listPendingMessagesResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "listPendingMessagesResponse")
    @WebMethod
    public ListPendingMessagesResponse listPendingMessages(
        @WebParam(partName = "listPendingMessagesRequest", name = "listPendingMessagesRequest", targetNamespace = "http://org.ecodex.backend/1_1/")
        java.lang.Object listPendingMessagesRequest
    ) throws ListPendingMessagesFault;

    @WebMethod
    public void downloadMessage(
        @WebParam(partName = "downloadMessageRequest", name = "downloadMessageRequest", targetNamespace = "http://org.ecodex.backend/1_1/")
        DownloadMessageRequest downloadMessageRequest,
        @WebParam(partName = "downloadMessageResponse", mode = WebParam.Mode.OUT, name = "downloadMessageResponse", targetNamespace = "http://org.ecodex.backend/1_1/")
        javax.xml.ws.Holder<DownloadMessageResponse> downloadMessageResponse,
        @WebParam(partName = "ebMSHeaderInfo", mode = WebParam.Mode.OUT, name = "Messaging", targetNamespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", header = true)
        javax.xml.ws.Holder<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging> ebMSHeaderInfo
    ) throws DownloadMessageFault;
}
