
CREATE USER smp IDENTIFIED BY "test" DEFAULT TABLESPACE users QUOTA UNLIMITED ON users; 
GRANT CREATE SESSION TO smp;
GRANT CREATE TABLE TO smp;
GRANT CREATE VIEW TO smp;
GRANT CREATE SEQUENCE TO smp;
GRANT SELECT ON PENDING_TRANS$ TO smp;

