---
excludes:
  paths:
    - pattern: ".mvn/**"
      reason: "BUILD_TOOL_OF"
      comment: "This directory contains Maven build tool."

    - pattern: "domismp-tests/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "smp-examples/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "smp-soapui-tests/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "smp-wls-deploy/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: ".ort.yml"
      reason: "DOCUMENTATION_OF"
      comment: "The file is a oss review toolkit configuration file."

    - pattern: "license/**"
      reason: "DOCUMENTATION_OF"
      comment: "Contains only text files of different third-party licenses."

    - pattern: "Notice.md"
      reason: "DOCUMENTATION_OF"
      comment: "Third-party license notice file."

  scopes:
    - pattern: "checkstyle"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Packages for code styling checks (testing) only."

    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "jacocoAgent"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "jacocoAnt"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."

    - pattern: "annotationProcessor"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileClasspath"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileOnly"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: ".*EUPL-1.2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore will not be an issue."
    - message: ".*EUPL-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and EUPL-1.1 is upward compatible and therefore not an issue."
    - message: "proprietary-free license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "property:non-commercial license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: ".*license LicenseRef-scancode-sun-prop-non-commercial in Maven:org.apache.geronimo.specs:geronimo-jta_1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These refer to such older versions schema files contained in the source distribution which are not used and distributed, therefore the license is complied with."
    - message: ".*license LicenseRef-scancode-sun-prop-non-commercial in Maven:org.apache.xmlbeans:xmlbeans:5.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These refer to such older versions schema files (in tags 1.0.0 - 1.0.1) contained in the source distribution which are not used and distributed, therefore the license is complied with."
    - message: ".*LicenseRef-scancode-sun-jsr-spec-04-2006.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: "proprietary-free license LicenseRef-IBM-US-Government-Restriction in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "copyleft-strong license GPL-2.0-or-later WITH Autoconf-exception-2.0 in Maven:antlr:antlr:2.7.7."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The license requires distribution under GPL terms but provides an exception for projects using Autoconf-generated configuration scripts, permitting them to be licensed under the same terms as the rest of the project."
    - message: ".*GPL-2.0-only WITH Universal-FOSS-exception-1.0.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with Universal FOSS Exception 1.0 is acceptable. The exception allows for compatible linking with other FOSS projects."
    - message: ".*GPL-2.0-only WITH LicenseRef-scancode-mysql-linking-exception-2018.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with LicenseRef-scancode-mysql-linking-exception-2018. The exception allows for compatible linking with other FOSS projects."
    - message: ".*Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Problematic files contain lists of different third-party licenses."
    - message: "copyleft-LGPL license LGPL-2.1-or-later in Maven:org.niis:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:antlr:antlr:2.7.7."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The file is deemed to be separate and distinct from the other parts of the package and therefore seen as mere aggregation. The license obligations of GPL-2.0-or-later do not cover the whole."
    - message: "copyleft-strong license GPL-2.0-only in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-LGPL license LGPL-2.1-only in Maven:org.niis:harmonysmp:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "copyleft-LGPL license LGPL-2.1-or-later in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "copyleft-module-level license EPL-1.0 in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-LGPL license LGPL-3.0-only in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-3.0-only is compatible with the main license."
    - message: "copyleft-LGPL license LGPL-3.0-only in Maven:org.niis:harmonysmp-angular:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-3.0-only is compatible with the main license."
    - message: "copyleft-LGPL license LGPL-3.0-only in NPM::smp-builders:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-3.0-only is compatible with the main license."
    - message: "copyleft-module-level license EPL-1.0 in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-file-level license EPL-2.0 in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-module-level license GPL-2.0-only WITH Classpath-exception-2.0 in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-only in NPM::smp-builders:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "Strong copyleft in open source project code GPL-2.0-or-later in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "Strong copyleft in open source project code GPL-2.0-only in Maven:org.niis:harmonysmp-modules:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "Strong copyleft in open source project code GPL-2.0-only in Maven:org.niis:harmonysmp-angular:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-only in Maven:org.niis:harmonysmp-angular:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:eu.europa.ec.bdmsl:bdmsl-api:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:eu.europa.ec.edelivery:edelivery-springsecurity-2-way-ssl-auth:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-only in Maven:eu.europa.ec.bdmsl:bdmsl-api:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-only in Maven:eu.europa.ec.edelivery:edelivery-springsecurity-2-way-ssl-auth:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.glassfish.jaxb:jaxb-runtime:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.glassfish.jaxb:jaxb-core:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.glassfish.jaxb:txw2:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.glassfish.jaxb:jaxb-xjc:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.glassfish.jaxb:xsom:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.glassfish.jaxb:codemodel:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:com.sun.xml.bind.external:relaxng-datatype:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:com.sun.xml.bind.external:rngom:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:com.sun.xml.dtd-parser:dtd-parser:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:com.mysql:mysql-connector-j:9.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The declared license is actually GPL-2.0-only WITH Universal-FOSS-exception-1.0."
    - message: "copyleft-strong license GPL-2.0-only in Maven:org.eclipse.angus:angus-mail:2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The declared license is actually EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR BSD-3-Clause."

license_choices:
  repository_license_choices:
    - given: "EPL-1.0 OR LGPL-2.1-or-later OR GPL-2.0-or-later OR Apache-2.0 OR BSD-2-Clause"
      choice: "Apache-2.0"
