---
excludes:
  paths:
    - pattern: ".mvn/**"
      reason: "BUILD_TOOL_OF"
      comment: "This directory contains Maven build tool."

    - pattern: "domismp-tests/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "smp-examples/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "smp-wls-deploy/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

  scopes:
    - pattern: "checkstyle"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Packages for code styling checks (testing) only."

    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "jacocoAgent"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "jacocoAnt"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."

    - pattern: "annotationProcessor"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileClasspath"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileOnly"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: ".*EUPL-1.2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore will not be an issue."
    - message: ".*EUPL-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and EUPL-1.1 is upward compatible and therefore not an issue."
    - message: ".*GPL-2.0-only WITH Universal-FOSS-exception-1.0.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with Universal FOSS Exception 1.0 is acceptable. The exception allows for compatible linking with other FOSS projects."
    - message: ".*GPL-2.0-only WITH LicenseRef-scancode-mysql-linking-exception-2018.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with LicenseRef-scancode-mysql-linking-exception-2018. The exception allows for compatible linking with other FOSS projects."
    - message: "copyleft-strong license CC-BY-SA-3.0 in Maven:org.freemarker:freemarker:2.3.32."
      reason: "CANT_FIX_EXCEPTION"
      comment: "License is in a license information file. The license defines that fonts used in documentation are under the concluded license and therefore is not an issue."
    - message: ".*CC-BY-NC-SA-2.5 in Maven:ch.qos.logback:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "The file is a template file and therefore an example file and not a redistributable artifact."
    - message: ".*LicenseRef-scancode-ecma-documentation.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "The LicenseRef-scancode-ecma-documentation license allows redistributing without modifications. As long as the files licensed with said license is redistributed without modifications, the violation is acceptable."
    - message: ".*LicenseRef-scancode-ms-specification.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "The LicenseRef-scancode-ecma-documentation license allows redistributing without modifications. As long as the files licensed with said license is redistributed without modifications, the violation is acceptable."
    - message: ".*LicenseRef-scancode-jsr-107-jcache-spec.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: ".*LicenseRef-scancode-sun-jsr-spec-04-2006.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: ".*LicenseRef-scancode-sun-sdk-spec-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:javax.xml.bind:jaxb-api:2.3.1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "This is a specification license from Bea Systems, Inc., a company later acquired by Oracle."
    - message: "proprietary-free license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "proprietary-free license LicenseRef-IBM-US-Government-Restriction in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "property:non-commercial license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "proprietary-free license LicenseRef-doubleopen-jsr-356-websocket-spec in Maven:org.apache.cxf:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The Java API for Websocket (JSR-356) Specification is under a limited license from Oracle - as these files are not modified the implementation should satisfy the requirements for a compliant implementation. Therefore the license conditions are satisfied."
    - message: ".*license LicenseRef-scancode-sun-prop-non-commercial in Maven:org.apache.geronimo.specs:geronimo-jta_1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These refer to such older versions schema files contained in the source distribution which are not used and distributed, therefore the license is complied with."
    - message: ".*license LicenseRef-scancode-sun-prop-non-commercial in Maven:org.apache.xmlbeans:xmlbeans:5.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These refer to such older versions schema files (in tags 1.0.0 - 1.0.1) contained in the source distribution which are not used and distributed, therefore the license is complied with."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:org.apache.xmlbeans:xmlbeans:5.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These refer to such older versions schema and other files (in tag 1.0.0 and tags 2.0.0 - 2.6.0) contained in the source distribution which are not used and distributed, therefore the license is complied with."

license_choices:
  repository_license_choices:
    - given: "BSD-3-Clause AND Apache-2.0 AND (GPL-2.0-only OR GPL-2.0-only WITH Classpath-exception-2.0) AND MIT"
      choice: "BSD-3-Clause AND Apache-2.0 AND GPL-2.0-only WITH Classpath-exception-2.0 AND MIT"
    - given: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND MIT AND SAX-PD AND EPL-1.0 AND (Apache-2.0 OR Apache-1.1 OR BSD-3-Clause OR LicenseRef-scancode-public-domain OR LicenseRef-scancode-indiana-extreme) AND (MIT OR GPL-1.0-or-later)"
      choice: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND MIT AND SAX-PD AND EPL-1.0 AND Apache-2.0 AND MIT"
