-- Rollback script for the provided MySQL schema changes
START TRANSACTION;
SET @OLD_FK_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

-- 1) Drop foreign keys
ALTER TABLE SMP_DOCUMENT_CERTIFICATE DROP FOREIGN KEY FKdo996u5n5vqp9950jbrd32tpv;
ALTER TABLE SMP_DOCUMENT_CERTIFICATE_AUD DROP FOREIGN KEY FKlfwn1ehct3domxnwc1dr3mx4g;
ALTER TABLE SMP_DOMAIN_DOC_TMPL DROP FOREIGN KEY FKg4ci2nee5nvm2tbdbpkeom53m;
ALTER TABLE SMP_DOMAIN_DOC_TMPL DROP FOREIGN KEY FK8dwm6w0x0rdiouvt74i07s9u5;
ALTER TABLE SMP_DOMAIN_DOC_TMPL DROP FOREIGN KEY FK45eaf7nmo1dem40af2dw27jh5;
ALTER TABLE SMP_DOMAIN_DOC_TMPL_AUD DROP FOREIGN KEY FKb1dw4r0rpj3jdtff4jc7gn046;
ALTER TABLE SMP_PERIODICAL_ALERT_AUD DROP FOREIGN KEY FK7qyb720heygkwc5mmpaer2iou;

-- 2) Drop UNIQUE constraints / indexes added by the upgrade
-- MySQL implements UNIQUE constraints as indexes; drop the indexes by name.
ALTER TABLE SMP_DOCUMENT_CERTIFICATE DROP INDEX UK7gl0tu846ixaiplii4tku1cqc;
ALTER TABLE SMP_PERIODICAL_ALERT DROP INDEX SMP_ALERT_COMPOSITE_IDX;
ALTER TABLE SMP_SUBRESOURCE_DEF DROP INDEX SMP_RESDEF_UNIQ_IDENTIFIER;

-- 3) Drop audit & main tables that were created
DROP TABLE IF EXISTS SMP_PERIODICAL_ALERT_AUD;
DROP TABLE IF EXISTS SMP_PERIODICAL_ALERT;
DROP TABLE IF EXISTS SMP_DOMAIN_DOC_TMPL_AUD;
DROP TABLE IF EXISTS SMP_DOMAIN_DOC_TMPL;
DROP TABLE IF EXISTS SMP_DOCUMENT_CERTIFICATE_AUD;
DROP TABLE IF EXISTS SMP_DOCUMENT_CERTIFICATE;

-- 4) Drop columns added to existing tables (if they exist)
ALTER TABLE SMP_DOMAIN DROP COLUMN ENABLE_DOMAIN_TRUSTSTORE;
ALTER TABLE SMP_DOMAIN DROP COLUMN SML_CLIENT_KEY_CHANGE_ALIAS;
ALTER TABLE SMP_DOMAIN DROP COLUMN SML_CLIENT_KEY_CHANGE_DATE;
ALTER TABLE SMP_DOMAIN DROP COLUMN SML_ENABLE_URL_DOMAIN_CODE_SUFFIX;

ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN ENABLE_DOMAIN_TRUSTSTORE;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN SML_CLIENT_KEY_CHANGE_ALIAS;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN SML_CLIENT_KEY_CHANGE_DATE;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN SML_ENABLE_URL_DOMAIN_CODE_SUFFIX;

ALTER TABLE SMP_RESOURCE_DEF DROP COLUMN URL_SEGMENT_OPTIONAL;
ALTER TABLE SMP_RESOURCE_DEF_AUD DROP COLUMN URL_SEGMENT_OPTIONAL;
ALTER TABLE SMP_SUBRESOURCE_DEF DROP COLUMN URL_SEGMENT_OPTIONAL;
ALTER TABLE SMP_SUBRESOURCE_DEF_AUD DROP COLUMN URL_SEGMENT_OPTIONAL;

-- 5) Revert enum columns back to VARCHAR(255) (adjust sizes/types to match original schema if you know them)
ALTER TABLE SMP_ALERT MODIFY ALERT_LEVEL VARCHAR(255);
ALTER TABLE SMP_ALERT MODIFY ALERT_STATUS VARCHAR(255);
ALTER TABLE SMP_ALERT MODIFY ALERT_TYPE VARCHAR(255);

ALTER TABLE SMP_ALERT_AUD MODIFY ALERT_LEVEL VARCHAR(255);
ALTER TABLE SMP_ALERT_AUD MODIFY ALERT_STATUS VARCHAR(255);
ALTER TABLE SMP_ALERT_AUD MODIFY ALERT_TYPE VARCHAR(255);

ALTER TABLE SMP_CREDENTIAL MODIFY CREDENTIAL_TARGET VARCHAR(255);
ALTER TABLE SMP_CREDENTIAL MODIFY CREDENTIAL_TYPE VARCHAR(255);
ALTER TABLE SMP_CREDENTIAL_AUD MODIFY CREDENTIAL_TARGET VARCHAR(255);
ALTER TABLE SMP_CREDENTIAL_AUD MODIFY CREDENTIAL_TYPE VARCHAR(255);

ALTER TABLE SMP_RESOURCE MODIFY VISIBILITY VARCHAR(128);
ALTER TABLE SMP_RESOURCE_AUD MODIFY VISIBILITY VARCHAR(128);

ALTER TABLE SMP_DOCUMENT_PROPERTY MODIFY PROPERTY_TYPE VARCHAR(64);
ALTER TABLE SMP_DOCUMENT_PROPERTY_AUD MODIFY PROPERTY_TYPE VARCHAR(64);

ALTER TABLE SMP_DOCUMENT_VERSION MODIFY STATUS VARCHAR(255);
ALTER TABLE SMP_DOCUMENT_VERSION_AUD MODIFY STATUS VARCHAR(255);

ALTER TABLE SMP_DOCUMENT_VERSION_EVENT MODIFY EVENT_SOURCE VARCHAR(255);
ALTER TABLE SMP_DOCUMENT_VERSION_EVENT MODIFY EVENT_TYPE VARCHAR(255);
ALTER TABLE SMP_DOCUMENT_VERSION_EVENT MODIFY EVENT_STATUS VARCHAR(255);

ALTER TABLE SMP_DOMAIN MODIFY VISIBILITY VARCHAR(64);
ALTER TABLE SMP_DOMAIN_AUD MODIFY VISIBILITY VARCHAR(64);

ALTER TABLE SMP_GROUP MODIFY VISIBILITY VARCHAR(128);
ALTER TABLE SMP_GROUP_AUD MODIFY VISIBILITY VARCHAR(128);

ALTER TABLE SMP_DOMAIN_MEMBER MODIFY MEMBERSHIP_ROLE VARCHAR(64);
ALTER TABLE SMP_DOMAIN_MEMBER_AUD MODIFY MEMBERSHIP_ROLE VARCHAR(64);
ALTER TABLE SMP_GROUP_MEMBER MODIFY MEMBERSHIP_ROLE VARCHAR(64);
ALTER TABLE SMP_GROUP_MEMBER_AUD MODIFY MEMBERSHIP_ROLE VARCHAR(64);

ALTER TABLE SMP_USER MODIFY APPLICATION_ROLE VARCHAR(256);
ALTER TABLE SMP_USER_AUD MODIFY APPLICATION_ROLE VARCHAR(256);


SET FOREIGN_KEY_CHECKS = @OLD_FK_CHECKS;

-- Done
COMMIT;