-- 1. Add new sequences
CREATE SEQUENCE SMP_DOMAIN_DOC_TMPL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SMP_PERIODICAL_ALERT_SEQ START WITH 1 INCREMENT BY 1;

-- 2. Add new tables
create table SMP_DOCUMENT_CERTIFICATE (
      ID number(19,0) not null,
      CREATED_ON timestamp(6) with time zone not null,
      LAST_UPDATED_ON timestamp(6) with time zone not null,
      CERTIFICATE_ID varchar2(1024 char) unique,
      ISSUER varchar2(1024 char),
      PEM_ENCODED_CERT clob,
      SERIALNUMBER varchar2(128 char),
      SUBJECT varchar2(1024 char),
      VALID_FROM timestamp(6) with time zone,
      VALID_TO timestamp(6) with time zone,
      primary key (ID)
);

comment on column SMP_DOCUMENT_CERTIFICATE.ID is
        'Shared primary key with master table SMP_DOC_PROP_SEQ';

comment on column SMP_DOCUMENT_CERTIFICATE.CERTIFICATE_ID is
    'Formatted Certificate id using tags: cn, o, c and serialNumber';

comment on column SMP_DOCUMENT_CERTIFICATE.ISSUER is
    'Certificate issuer (canonical form)';

comment on column SMP_DOCUMENT_CERTIFICATE.PEM_ENCODED_CERT is
    'PEM encoded certificate';

comment on column SMP_DOCUMENT_CERTIFICATE.SERIALNUMBER is
    'Certificate serial number';

comment on column SMP_DOCUMENT_CERTIFICATE.SUBJECT is
    'Certificate subject (canonical form)';

comment on column SMP_DOCUMENT_CERTIFICATE.VALID_FROM is
    'Certificate valid from date.';

comment on column SMP_DOCUMENT_CERTIFICATE.VALID_TO is
    'Certificate valid to date.';

create table SMP_DOCUMENT_CERTIFICATE_AUD (
      ID number(19,0) not null,
      REV number(19,0) not null,
      REVTYPE number(3,0),
      CREATED_ON timestamp(6) with time zone,
      LAST_UPDATED_ON timestamp(6) with time zone,
      CERTIFICATE_ID varchar2(1024 char),
      ISSUER varchar2(1024 char),
      PEM_ENCODED_CERT clob,
      SERIALNUMBER varchar2(128 char),
      SUBJECT varchar2(1024 char),
      VALID_FROM timestamp(6) with time zone,
      VALID_TO timestamp(6) with time zone,
      primary key (REV, ID)
);

create table SMP_DOMAIN_DOC_TMPL (
     ID number(19,0) not null,
     CREATED_ON timestamp(6) with time zone not null,
     LAST_UPDATED_ON timestamp(6) with time zone not null,
     DOCUMENT_LEVEL varchar2(255 char) not null check (DOCUMENT_LEVEL in ('RESOURCE','SUBRESOURCE')),
     FK_DOCUMENT_ID number(19,0) not null,
     FK_DOREDEF_ID number(19,0) not null,
     FK_SUREDEF_ID number(19,0),
     primary key (ID)
);

comment on column SMP_DOMAIN_DOC_TMPL.ID is
    'Unique domain document template id';

comment on column SMP_DOMAIN_DOC_TMPL.DOCUMENT_LEVEL is
    'Document level type - resource or subresource';

create table SMP_DOMAIN_DOC_TMPL_AUD (
    ID number(19,0) not null,
    REV number(19,0) not null,
    REVTYPE number(3,0),
    CREATED_ON timestamp(6) with time zone,
    LAST_UPDATED_ON timestamp(6) with time zone,
    DOCUMENT_LEVEL varchar2(255 char) check (DOCUMENT_LEVEL in ('RESOURCE','SUBRESOURCE')),
    FK_DOCUMENT_ID number(19,0),
    FK_DOREDEF_ID number(19,0),
    FK_SUREDEF_ID number(19,0),
    primary key (REV, ID)
);

create table SMP_PERIODICAL_ALERT (
    ID number(19,0) not null,
    CREATED_ON timestamp(6) with time zone not null,
    LAST_UPDATED_ON timestamp(6) with time zone not null,
    ALERT_SCOPE varchar2(255 char) check (ALERT_SCOPE in ('USER_CREDENTIAL','SYSTEM_TRUSTSTORE','SYSTEM_KEYSTORE')),
    ENTITY_IDENTIFIER varchar2(255 char),
    ENTITY_TYPE varchar2(255 char) check (ENTITY_TYPE in ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','SYSTEM_CERTIFICATE')),
    LAST_ALERT_ON timestamp(6) with time zone,
    primary key (ID),
    constraint SMP_ALERT_COMPOSITE_IDX unique (ENTITY_IDENTIFIER, ENTITY_TYPE, ALERT_SCOPE)
);

comment on column SMP_PERIODICAL_ALERT.ID is
    'Unique periodical alert id';

comment on column SMP_PERIODICAL_ALERT.ENTITY_IDENTIFIER is
    'Entity identifier for which the alert is sent, credential database id, certificate alias, etc.';

comment on column SMP_PERIODICAL_ALERT.LAST_ALERT_ON is
    'Date and time when the last alert was sent for this entity';

create table SMP_PERIODICAL_ALERT_AUD (
    ID number(19,0) not null,
    REV number(19,0) not null,
    REVTYPE number(3,0),
    CREATED_ON timestamp(6) with time zone,
    LAST_UPDATED_ON timestamp(6) with time zone,
    ALERT_SCOPE varchar2(255 char) check (ALERT_SCOPE in ('USER_CREDENTIAL','SYSTEM_TRUSTSTORE','SYSTEM_KEYSTORE')),
    ENTITY_IDENTIFIER varchar2(255 char),
    ENTITY_TYPE varchar2(255 char) check (ENTITY_TYPE in ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','SYSTEM_CERTIFICATE')),
    LAST_ALERT_ON timestamp(6) with time zone,
    primary key (REV, ID)
);

-- 3. Add new columns to existing tables
ALTER TABLE SMP_DOMAIN ADD (
    ENABLE_DOMAIN_TRUSTSTORE number(1,0) check (ENABLE_DOMAIN_TRUSTSTORE in (0,1)),
    SML_CLIENT_KEY_CHANGE_ALIAS varchar2(255 char),
    SML_CLIENT_KEY_CHANGE_DATE timestamp(6) with time zone,
    SML_ENABLE_URL_DOMAIN_CODE_SUFFIX number(1,0) check (SML_ENABLE_URL_DOMAIN_CODE_SUFFIX in (0,1))
);

ALTER TABLE SMP_DOMAIN_AUD ADD (
    ENABLE_DOMAIN_TRUSTSTORE number(1,0),
    SML_CLIENT_KEY_CHANGE_ALIAS VARCHAR2(255 CHAR),
    SML_CLIENT_KEY_CHANGE_DATE timestamp(6) WITH TIME ZONE,
    SML_ENABLE_URL_DOMAIN_CODE_SUFFIX number(1,0)
);

ALTER TABLE SMP_RESOURCE_DEF ADD (
    URL_SEGMENT_OPTIONAL varchar2(128 char)
);

ALTER TABLE SMP_RESOURCE_DEF_AUD ADD (
    URL_SEGMENT_OPTIONAL varchar2(128 char)
);

ALTER TABLE SMP_SUBRESOURCE_DEF ADD (
    URL_SEGMENT_OPTIONAL varchar2(128 char)
);

ALTER TABLE SMP_SUBRESOURCE_DEF_AUD ADD (
    URL_SEGMENT_OPTIONAL varchar2(128 char)
);

-- 4. Add/replace CHECK constraints
ALTER TABLE SMP_ALERT MODIFY (
    ALERT_LEVEL VARCHAR2(255 CHAR) CHECK (ALERT_LEVEL IN ('HIGH','MEDIUM','LOW')),
    ALERT_STATUS VARCHAR2(255 CHAR) CHECK (ALERT_STATUS IN ('PROCESS','SUCCESS','FAILED')),
    ALERT_TYPE VARCHAR2(255 CHAR) CHECK (ALERT_TYPE IN ('TEST_ALERT','CREDENTIAL_IMMINENT_EXPIRATION','CREDENTIAL_EXPIRED','CREDENTIAL_SUSPENDED','CREDENTIAL_VERIFICATION_FAILED','CREDENTIAL_REQUEST_RESET','CREDENTIAL_CHANGED','SYSTEM_CERTIFICATE_IMMINENT_EXPIRATION','SYSTEM_CERTIFICATE_EXPIRED','USER_CREATED_CONFIRMATION','USER_CREATED','USER_UPDATED','USER_CREATED_EU_LOGIN','RESOURCE_DOCUMENT_ACTION','SUBRESOURCE_DOCUMENT_ACTION','RESOURCE_DOCUMENT_REVIEW_ACTION','SUBRESOURCE_DOCUMENT_REVIEW_ACTION'))
);

ALTER TABLE SMP_ALERT_AUD MODIFY (
    ALERT_LEVEL VARCHAR2(255 CHAR) CHECK (ALERT_LEVEL IN ('HIGH','MEDIUM','LOW')),
    ALERT_STATUS VARCHAR2(255 CHAR) CHECK (ALERT_STATUS IN ('PROCESS','SUCCESS','FAILED')),
    ALERT_TYPE VARCHAR2(255 CHAR) CHECK (ALERT_TYPE IN ('TEST_ALERT','CREDENTIAL_IMMINENT_EXPIRATION','CREDENTIAL_EXPIRED','CREDENTIAL_SUSPENDED','CREDENTIAL_VERIFICATION_FAILED','CREDENTIAL_REQUEST_RESET','CREDENTIAL_CHANGED','SYSTEM_CERTIFICATE_IMMINENT_EXPIRATION','SYSTEM_CERTIFICATE_EXPIRED','USER_CREATED_CONFIRMATION','USER_CREATED','USER_UPDATED','USER_CREATED_EU_LOGIN','RESOURCE_DOCUMENT_ACTION','SUBRESOURCE_DOCUMENT_ACTION','RESOURCE_DOCUMENT_REVIEW_ACTION','SUBRESOURCE_DOCUMENT_REVIEW_ACTION'))
    );

ALTER TABLE SMP_CREDENTIAL MODIFY (
    CREDENTIAL_ACTIVE NUMBER(1,0) CHECK (CREDENTIAL_ACTIVE IN (0,1)),
    CREDENTIAL_TARGET VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TARGET IN ('UI','REST_API')),
    CREDENTIAL_TYPE VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TYPE IN ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','CAS'))
    );

ALTER TABLE SMP_CREDENTIAL_AUD MODIFY (
    CREDENTIAL_ACTIVE NUMBER(1,0) CHECK (CREDENTIAL_ACTIVE IN (0,1)),
    CREDENTIAL_TARGET VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TARGET IN ('UI','REST_API')),
    CREDENTIAL_TYPE VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TYPE IN ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','CAS'))
    );

ALTER TABLE SMP_DOCUMENT_PROPERTY MODIFY (
    PROPERTY_TYPE VARCHAR2(64 CHAR) CHECK (PROPERTY_TYPE IN ('STRING','DATETIME','LIST_STRING','MAP_STRING','INTEGER','BOOLEAN','REGEXP','CRON_EXPRESSION','EMAIL','FILENAME','PATH','URL','CERTIFICATE'))
    );

ALTER TABLE SMP_DOCUMENT_PROPERTY_AUD MODIFY (
    PROPERTY_TYPE VARCHAR2(64 CHAR) CHECK (PROPERTY_TYPE IN ('STRING','DATETIME','LIST_STRING','MAP_STRING','INTEGER','BOOLEAN','REGEXP','CRON_EXPRESSION','EMAIL','FILENAME','PATH','URL','CERTIFICATE'))
    );

ALTER TABLE SMP_DOCUMENT_VERSION MODIFY (
    STATUS VARCHAR2(255 CHAR) CHECK (STATUS IN ('DRAFT','PUBLISHED','RETIRED','UNDER_REVIEW','APPROVED','REJECTED'))
    );

ALTER TABLE SMP_DOCUMENT_VERSION_AUD MODIFY (
    STATUS VARCHAR2(255 CHAR) CHECK (STATUS IN ('DRAFT','PUBLISHED','RETIRED','UNDER_REVIEW','APPROVED','REJECTED'))
    );

ALTER TABLE SMP_DOCUMENT_VERSION_EVENT MODIFY (
    EVENT_SOURCE VARCHAR2(255 CHAR) CHECK (EVENT_SOURCE IN ('UI','REST_API','CRON','PLUGIN','OTHER')),
    EVENT_TYPE VARCHAR2(255 CHAR) CHECK (EVENT_TYPE IN ('CREATE','UPDATE','PUBLISH','REQUEST_REVIEW','RETIRE','APPROVE','REJECT','ERROR','SETTINGS_CHANGE')),
    EVENT_STATUS VARCHAR2(255 CHAR) CHECK (EVENT_STATUS IN ('DRAFT','PUBLISHED','RETIRED','UNDER_REVIEW','APPROVED','REJECTED'))
    );

ALTER TABLE SMP_DOMAIN MODIFY (
    VISIBILITY VARCHAR2(64 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE')),
    SML_CLIENT_CERT_AUTH NUMBER(1,0) CHECK (SML_CLIENT_CERT_AUTH IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_AUD MODIFY (
    VISIBILITY VARCHAR2(64 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE')),
    SML_CLIENT_CERT_AUTH NUMBER(1,0) CHECK (SML_CLIENT_CERT_AUTH IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_CONFIGURATION MODIFY (
    SYSTEM_DEFAULT NUMBER(1,0) CHECK (SYSTEM_DEFAULT IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_CONFIGURATION_AUD MODIFY (
    SYSTEM_DEFAULT NUMBER(1,0) CHECK (SYSTEM_DEFAULT IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_MEMBER MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_DOMAIN_MEMBER_AUD MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_GROUP MODIFY (
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_GROUP_AUD MODIFY (
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_GROUP_MEMBER MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_GROUP_MEMBER_AUD MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_RESOURCE MODIFY (
    REVIEW_ENABLED NUMBER(1,0) CHECK (REVIEW_ENABLED IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1)),
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_RESOURCE_AUD MODIFY (
    REVIEW_ENABLED NUMBER(1,0) CHECK (REVIEW_ENABLED IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1)),
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_RESOURCE_MEMBER MODIFY (
    PERMISSION_REVIEW NUMBER(1,0) CHECK (PERMISSION_REVIEW IN (0,1)),
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_RESOURCE_MEMBER_AUD MODIFY (
    PERMISSION_REVIEW NUMBER(1,0) CHECK (PERMISSION_REVIEW IN (0,1)),
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_USER MODIFY (
    ACTIVE NUMBER(1,0) CHECK (ACTIVE IN (0,1)),
    APPLICATION_ROLE VARCHAR2(256 CHAR) CHECK (APPLICATION_ROLE IN ('USER','SYSTEM_ADMIN'))
    );

ALTER TABLE SMP_USER_AUD MODIFY (
    ACTIVE NUMBER(1,0) CHECK (ACTIVE IN (0,1)),
    APPLICATION_ROLE VARCHAR2(256 CHAR) CHECK (APPLICATION_ROLE IN ('USER','SYSTEM_ADMIN'))
    );

-- 5. Add/replace UNIQUE constraints (if not already present)
-- Step 1: Drop the existing unique constraint
ALTER TABLE SMP_CERTIFICATE DROP CONSTRAINT UK_3x3rvf6hkim9fg16caurkgg6f;
ALTER TABLE SMP_EXTENSION DROP CONSTRAINT UK_p4vfhgs7fvuo6uebjsuqxrglg;
ALTER TABLE SMP_RESOURCE_DEF DROP CONSTRAINT UK_k7l5fili2mmhgslv77afg4myo;
ALTER TABLE SMP_RESOURCE_DEF DROP CONSTRAINT UK_jjbctkhd4h0u9whb1i9wbxwoe;
ALTER TABLE SMP_SUBRESOURCE_DEF DROP CONSTRAINT UK_pmdcnfwm5in2q9ky0b6dlgqvi;
ALTER TABLE SMP_USER DROP CONSTRAINT UK_rt1f0anklfo05lt0my05fqq6;

-- Step 2: Modify the column to include inline UNIQUE constraint
ALTER TABLE SMP_CERTIFICATE MODIFY CERTIFICATE_ID VARCHAR2(1024 CHAR) UNIQUE;
ALTER TABLE SMP_EXTENSION MODIFY IDENTIFIER varchar2(128 char) UNIQUE;
ALTER TABLE SMP_RESOURCE_DEF MODIFY IDENTIFIER varchar2(128 char) UNIQUE;
ALTER TABLE SMP_RESOURCE_DEF MODIFY URL_SEGMENT varchar2(128 char) UNIQUE;
ALTER TABLE SMP_SUBRESOURCE_DEF MODIFY IDENTIFIER varchar2(128 char) UNIQUE;
ALTER TABLE SMP_USER MODIFY USERNAME varchar2(64 char) UNIQUE;


-- 6. Add new foreign keys
ALTER TABLE SMP_DOCUMENT_CERTIFICATE
    ADD CONSTRAINT FKdo996u5n5vqp9950jbrd32tpv FOREIGN KEY (ID) REFERENCES SMP_DOCUMENT_PROPERTY;

ALTER TABLE SMP_DOCUMENT_CERTIFICATE_AUD
    ADD CONSTRAINT FKlfwn1ehct3domxnwc1dr3mx4g FOREIGN KEY (REV) REFERENCES SMP_REV_INFO;

ALTER TABLE SMP_DOMAIN_DOC_TMPL
    ADD CONSTRAINT FKg4ci2nee5nvm2tbdbpkeom53m FOREIGN KEY (FK_DOCUMENT_ID) REFERENCES SMP_DOCUMENT;

ALTER TABLE SMP_DOMAIN_DOC_TMPL
    ADD CONSTRAINT FK8dwm6w0x0rdiouvt74i07s9u5 FOREIGN KEY (FK_DOREDEF_ID) REFERENCES SMP_DOMAIN_RESOURCE_DEF;

ALTER TABLE SMP_DOMAIN_DOC_TMPL
    ADD CONSTRAINT FK45eaf7nmo1dem40af2dw27jh5 FOREIGN KEY (FK_SUREDEF_ID) REFERENCES SMP_SUBRESOURCE_DEF;

ALTER TABLE SMP_DOMAIN_DOC_TMPL_AUD
    ADD CONSTRAINT FKb1dw4r0rpj3jdtff4jc7gn046 FOREIGN KEY (REV) REFERENCES SMP_REV_INFO;

ALTER TABLE SMP_PERIODICAL_ALERT_AUD
    ADD CONSTRAINT FK7qyb720heygkwc5mmpaer2iou FOREIGN KEY (REV) REFERENCES SMP_REV_INFO;

-- END OF UPGRADE SCRIPT