-- WARNING Before executing this script, make sure user has enough privileges to create PROCEDURE!

-- 1. Rollback for sequence creation
drop sequence SMP_DOMAIN_DOC_TMPL_SEQ;
drop sequence SMP_PERIODICAL_ALERT_SEQ;

-- 2. Add new tables
drop table SMP_DOCUMENT_CERTIFICATE cascade constraints;
drop table SMP_DOCUMENT_CERTIFICATE_AUD cascade constraints;
drop table SMP_DOMAIN_DOC_TMPL cascade constraints;
drop table SMP_DOMAIN_DOC_TMPL_AUD cascade constraints;
drop table SMP_PERIODICAL_ALERT cascade constraints;
drop table SMP_PERIODICAL_ALERT_AUD cascade constraints;


-- 3. remove new columns from existing tables
ALTER TABLE SMP_DOMAIN DROP COLUMN ENABLE_DOMAIN_TRUSTSTORE;
ALTER TABLE SMP_DOMAIN DROP COLUMN SML_CLIENT_KEY_CHANGE_ALIAS;
ALTER TABLE SMP_DOMAIN DROP COLUMN SML_CLIENT_KEY_CHANGE_DATE;
ALTER TABLE SMP_DOMAIN DROP COLUMN SML_ENABLE_URL_DOMAIN_CODE_SUFFIX;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN ENABLE_DOMAIN_TRUSTSTORE;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN SML_CLIENT_KEY_CHANGE_ALIAS;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN SML_CLIENT_KEY_CHANGE_DATE;
ALTER TABLE SMP_DOMAIN_AUD DROP COLUMN SML_ENABLE_URL_DOMAIN_CODE_SUFFIX;
ALTER TABLE SMP_RESOURCE_DEF DROP COLUMN URL_SEGMENT_OPTIONAL;
ALTER TABLE SMP_RESOURCE_DEF_AUD DROP COLUMN URL_SEGMENT_OPTIONAL;
ALTER TABLE SMP_SUBRESOURCE_DEF DROP COLUMN URL_SEGMENT_OPTIONAL;
ALTER TABLE SMP_SUBRESOURCE_DEF_AUD DROP COLUMN URL_SEGMENT_OPTIONAL;

-- 4. remove check constraints from existing tables

-- 5. Add/replace CHECK constraints
ALTER TABLE SMP_ALERT MODIFY (
    ALERT_LEVEL VARCHAR2(255 CHAR) ,
    ALERT_STATUS VARCHAR2(255 CHAR),
    ALERT_TYPE VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_ALERT_AUD MODIFY (
    ALERT_LEVEL VARCHAR2(255 CHAR) ,
    ALERT_STATUS VARCHAR2(255 CHAR),
    ALERT_TYPE VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_CREDENTIAL MODIFY (
    CREDENTIAL_ACTIVE,
    CREDENTIAL_TARGET VARCHAR2(255 CHAR),
    CREDENTIAL_TYPE VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_CREDENTIAL_AUD MODIFY (
    CREDENTIAL_ACTIVE NUMBER(1,0),
    CREDENTIAL_TARGET VARCHAR2(255 CHAR),
    CREDENTIAL_TYPE VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_DOCUMENT_PROPERTY MODIFY (
    PROPERTY_TYPE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_DOCUMENT_PROPERTY_AUD MODIFY (
    PROPERTY_TYPE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_DOCUMENT_VERSION MODIFY (
    STATUS VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_DOCUMENT_VERSION_AUD MODIFY (
    STATUS VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_DOCUMENT_VERSION_EVENT MODIFY (
    EVENT_SOURCE VARCHAR2(255 CHAR),
    EVENT_TYPE VARCHAR2(255 CHAR),
    EVENT_STATUS VARCHAR2(255 CHAR)
);

ALTER TABLE SMP_DOMAIN MODIFY (
    VISIBILITY VARCHAR2(64 CHAR),
    SML_CLIENT_CERT_AUTH NUMBER(1,0),
    SML_REGISTERED NUMBER(1,0)
);

ALTER TABLE SMP_DOMAIN_AUD MODIFY (
    VISIBILITY VARCHAR2(64 CHAR),
    SML_CLIENT_CERT_AUTH NUMBER(1,0),
    SML_REGISTERED NUMBER(1,0)
);

ALTER TABLE SMP_DOMAIN_CONFIGURATION MODIFY (
    SYSTEM_DEFAULT NUMBER(1,0)
);

ALTER TABLE SMP_DOMAIN_CONFIGURATION_AUD MODIFY (
    SYSTEM_DEFAULT NUMBER(1,0)
);

ALTER TABLE SMP_DOMAIN_MEMBER MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_DOMAIN_MEMBER_AUD MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_GROUP MODIFY (
    VISIBILITY VARCHAR2(128 CHAR)
);

ALTER TABLE SMP_GROUP_AUD MODIFY (
    VISIBILITY VARCHAR2(128 CHAR)
);

ALTER TABLE SMP_GROUP_MEMBER MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_GROUP_MEMBER_AUD MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_RESOURCE MODIFY (
    REVIEW_ENABLED NUMBER(1,0),
    SML_REGISTERED NUMBER(1,0),
    VISIBILITY VARCHAR2(128 CHAR)
);

ALTER TABLE SMP_RESOURCE_AUD MODIFY (
    REVIEW_ENABLED NUMBER(1,0),
    SML_REGISTERED NUMBER(1,0),
    VISIBILITY VARCHAR2(128 CHAR)
);

ALTER TABLE SMP_RESOURCE_MEMBER MODIFY (
    PERMISSION_REVIEW NUMBER(1,0),
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_RESOURCE_MEMBER_AUD MODIFY (
    PERMISSION_REVIEW NUMBER(1,0),
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR)
);

ALTER TABLE SMP_USER MODIFY (
    ACTIVE NUMBER(1,0),
    APPLICATION_ROLE VARCHAR2(256 CHAR)
);

ALTER TABLE SMP_USER_AUD MODIFY (
    ACTIVE NUMBER(1,0),
    APPLICATION_ROLE VARCHAR2(256 CHAR)
);

-- 6. Add/replace UNIQUE constraints (if not already present)

-- Step 1.  Create a procedure to drop unique constraints on a given table and column
-- Step 1.  Create a procedure to drop unique constraints on a given table and column
CREATE OR REPLACE PROCEDURE drop_unique_constraints (
  p_table_name  IN VARCHAR2,
  p_column_name IN VARCHAR2
) AS
BEGIN
FOR r IN (
    SELECT c.constraint_name,
           c.table_name
    FROM user_constraints c
    JOIN user_cons_columns ucc
      ON c.constraint_name = ucc.constraint_name
     AND c.table_name = ucc.table_name
    WHERE c.constraint_type = 'U'
      AND c.table_name = UPPER(p_table_name)
      AND ucc.column_name = UPPER(p_column_name)
  ) LOOP
BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE ' || r.table_name || ' DROP CONSTRAINT ' || r.constraint_name;
DBMS_OUTPUT.PUT_LINE('Dropped constraint: ' || r.constraint_name || ' on ' || r.table_name);
EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error dropping constraint ' || r.constraint_name || ': ' || SQLERRM);
        -- continue with next constraint
END;
END LOOP;
END drop_unique_constraints;
/


-- Step 2.  Drop existing unique constraints on the specified columns
BEGIN
    drop_unique_constraints('SMP_CERTIFICATE', 'CERTIFICATE_ID');
    drop_unique_constraints('SMP_EXTENSION', 'IDENTIFIER');
    drop_unique_constraints('SMP_RESOURCE_DEF', 'IDENTIFIER');
    drop_unique_constraints('SMP_RESOURCE_DEF', 'URL_SEGMENT');
    drop_unique_constraints('SMP_SUBRESOURCE_DEF', 'IDENTIFIER');
    drop_unique_constraints('SMP_USER', 'USERNAME');
END;
/
-- drop the procedure drop_unique_constraints;
DROP PROCEDURE drop_unique_constraints;


-- Step 3: add back the unique constraints
alter table SMP_CERTIFICATE
    add constraint UK_3x3rvf6hkim9fg16caurkgg6f unique (CERTIFICATE_ID);
alter table SMP_EXTENSION
    add constraint UK_p4vfhgs7fvuo6uebjsuqxrglg unique (IDENTIFIER);
alter table SMP_RESOURCE_DEF
    add constraint UK_k7l5fili2mmhgslv77afg4myo unique (IDENTIFIER);
alter table SMP_RESOURCE_DEF
    add constraint UK_jjbctkhd4h0u9whb1i9wbxwoe unique (URL_SEGMENT);
alter table SMP_SUBRESOURCE_DEF
    add constraint UK_pmdcnfwm5in2q9ky0b6dlgqvi unique (IDENTIFIER);
alter table SMP_USER
    add constraint UK_rt1f0anklfo05lt0my05fqq6 unique (USERNAME);

-- END OF UPGRADE SCRIPT