-- 1. Add new sequences
CREATE SEQUENCE SMP_DOMAIN_DOC_TMPL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SMP_PERIODICAL_ALERT_SEQ START WITH 1 INCREMENT BY 1;

-- 2. Add new tables

CREATE TABLE SMP_DOMAIN_DOC_TMPL (
                                     ID NUMBER(19,0) NOT NULL,
                                     CREATED_ON TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                     LAST_UPDATED_ON TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                     DOCUMENT_LEVEL VARCHAR2(255 CHAR) NOT NULL CHECK (DOCUMENT_LEVEL IN ('RESOURCE','SUBRESOURCE')),
                                     FK_DOCUMENT_ID NUMBER(19,0) NOT NULL,
                                     FK_DOREDEF_ID NUMBER(19,0) NOT NULL,
                                     FK_SUREDEF_ID NUMBER(19,0),
                                     PRIMARY KEY (ID)
);

CREATE TABLE SMP_DOMAIN_DOC_TMPL_AUD (
                                         ID NUMBER(19,0) NOT NULL,
                                         REV NUMBER(19,0) NOT NULL,
                                         REVTYPE NUMBER(3,0),
                                         CREATED_ON TIMESTAMP(6) WITH TIME ZONE,
                                         LAST_UPDATED_ON TIMESTAMP(6) WITH TIME ZONE,
                                         DOCUMENT_LEVEL VARCHAR2(255 CHAR) CHECK (DOCUMENT_LEVEL IN ('RESOURCE','SUBRESOURCE')),
                                         FK_DOCUMENT_ID NUMBER(19,0),
                                         FK_DOREDEF_ID NUMBER(19,0),
                                         FK_SUREDEF_ID NUMBER(19,0),
                                         PRIMARY KEY (REV, ID)
);

CREATE TABLE SMP_PERIODICAL_ALERT (
                                      ID NUMBER(19,0) NOT NULL,
                                      CREATED_ON TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                      LAST_UPDATED_ON TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                      ALERT_SCOPE VARCHAR2(255 CHAR) CHECK (ALERT_SCOPE IN ('USER_CREDENTIAL','SYSTEM_TRUSTSTORE','SYSTEM_KEYSTORE')),
                                      ENTITY_IDENTIFIER VARCHAR2(255 CHAR),
                                      ENTITY_TYPE VARCHAR2(255 CHAR) CHECK (ENTITY_TYPE IN ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','SYSTEM_CERTIFICATE')),
                                      LAST_ALERT_ON TIMESTAMP(6) WITH TIME ZONE,
                                      PRIMARY KEY (ID),
                                      CONSTRAINT SMP_ALERT_COMPOSITE_IDX UNIQUE (ENTITY_IDENTIFIER, ENTITY_TYPE, ALERT_SCOPE)
);

CREATE TABLE SMP_PERIODICAL_ALERT_AUD (
                                          ID NUMBER(19,0) NOT NULL,
                                          REV NUMBER(19,0) NOT NULL,
                                          REVTYPE NUMBER(3,0),
                                          CREATED_ON TIMESTAMP(6) WITH TIME ZONE,
                                          LAST_UPDATED_ON TIMESTAMP(6) WITH TIME ZONE,
                                          ALERT_SCOPE VARCHAR2(255 CHAR) CHECK (ALERT_SCOPE IN ('USER_CREDENTIAL','SYSTEM_TRUSTSTORE','SYSTEM_KEYSTORE')),
                                          ENTITY_IDENTIFIER VARCHAR2(255 CHAR),
                                          ENTITY_TYPE VARCHAR2(255 CHAR) CHECK (ENTITY_TYPE IN ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','SYSTEM_CERTIFICATE')),
                                          LAST_ALERT_ON TIMESTAMP(6) WITH TIME ZONE,
                                          PRIMARY KEY (REV, ID)
);

CREATE TABLE SMP_DOCUMENT_CERTIFICATE (
                                          ID NUMBER(19,0) NOT NULL,
                                          CREATED_ON TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                          LAST_UPDATED_ON TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                          CERTIFICATE_ID VARCHAR2(1024 CHAR) UNIQUE,
                                          ISSUER VARCHAR2(1024 CHAR),
                                          PEM_ENCODED_CERT CLOB,
                                          SERIALNUMBER VARCHAR2(128 CHAR),
                                          SUBJECT VARCHAR2(1024 CHAR),
                                          VALID_FROM TIMESTAMP(6) WITH TIME ZONE,
                                          VALID_TO TIMESTAMP(6) WITH TIME ZONE,
                                          PRIMARY KEY (ID)
);

CREATE TABLE SMP_DOCUMENT_CERTIFICATE_AUD (
                                              ID NUMBER(19,0) NOT NULL,
                                              REV NUMBER(19,0) NOT NULL,
                                              REVTYPE NUMBER(3,0),
                                              CREATED_ON TIMESTAMP(6) WITH TIME ZONE,
                                              LAST_UPDATED_ON TIMESTAMP(6) WITH TIME ZONE,
                                              CERTIFICATE_ID VARCHAR2(1024 CHAR),
                                              ISSUER VARCHAR2(1024 CHAR),
                                              PEM_ENCODED_CERT CLOB,
                                              SERIALNUMBER VARCHAR2(128 CHAR),
                                              SUBJECT VARCHAR2(1024 CHAR),
                                              VALID_FROM TIMESTAMP(6) WITH TIME ZONE,
                                              VALID_TO TIMESTAMP(6) WITH TIME ZONE,
                                              PRIMARY KEY (REV, ID)
);

-- 3. Add new columns to existing tables

ALTER TABLE SMP_DOMAIN ADD (
    ENABLE_DOMAIN_TRUSTSTORE NUMBER(1,0) CHECK (ENABLE_DOMAIN_TRUSTSTORE IN (0,1)),
    SML_CLIENT_KEY_CHANGE_ALIAS VARCHAR2(255 CHAR),
    SML_CLIENT_KEY_CHANGE_DATE TIMESTAMP(6) WITH TIME ZONE,
    SML_ENABLE_URL_DOMAIN_CODE_SUFFIX NUMBER(1,0) CHECK (SML_ENABLE_URL_DOMAIN_CODE_SUFFIX IN (0,1))
);

-- 5. Add/replace CHECK constraints

ALTER TABLE SMP_ALERT MODIFY (
    ALERT_LEVEL VARCHAR2(255 CHAR) CHECK (ALERT_LEVEL IN ('HIGH','MEDIUM','LOW')),
    ALERT_STATUS VARCHAR2(255 CHAR) CHECK (ALERT_STATUS IN ('PROCESS','SUCCESS','FAILED')),
    ALERT_TYPE VARCHAR2(255 CHAR) CHECK (ALERT_TYPE IN ('TEST_ALERT','CREDENTIAL_IMMINENT_EXPIRATION','CREDENTIAL_EXPIRED','CREDENTIAL_SUSPENDED','CREDENTIAL_VERIFICATION_FAILED','CREDENTIAL_REQUEST_RESET','CREDENTIAL_CHANGED','SYSTEM_CERTIFICATE_IMMINENT_EXPIRATION','SYSTEM_CERTIFICATE_EXPIRED','USER_CREATED_CONFIRMATION','USER_CREATED','USER_UPDATED','USER_CREATED_EU_LOGIN','RESOURCE_DOCUMENT_ACTION','SUBRESOURCE_DOCUMENT_ACTION','RESOURCE_DOCUMENT_REVIEW_ACTION','SUBRESOURCE_DOCUMENT_REVIEW_ACTION'))
    );

ALTER TABLE SMP_ALERT_AUD MODIFY (
    ALERT_LEVEL VARCHAR2(255 CHAR) CHECK (ALERT_LEVEL IN ('HIGH','MEDIUM','LOW')),
    ALERT_STATUS VARCHAR2(255 CHAR) CHECK (ALERT_STATUS IN ('PROCESS','SUCCESS','FAILED')),
    ALERT_TYPE VARCHAR2(255 CHAR) CHECK (ALERT_TYPE IN ('TEST_ALERT','CREDENTIAL_IMMINENT_EXPIRATION','CREDENTIAL_EXPIRED','CREDENTIAL_SUSPENDED','CREDENTIAL_VERIFICATION_FAILED','CREDENTIAL_REQUEST_RESET','CREDENTIAL_CHANGED','SYSTEM_CERTIFICATE_IMMINENT_EXPIRATION','SYSTEM_CERTIFICATE_EXPIRED','USER_CREATED_CONFIRMATION','USER_CREATED','USER_UPDATED','USER_CREATED_EU_LOGIN','RESOURCE_DOCUMENT_ACTION','SUBRESOURCE_DOCUMENT_ACTION','RESOURCE_DOCUMENT_REVIEW_ACTION','SUBRESOURCE_DOCUMENT_REVIEW_ACTION'))
    );

ALTER TABLE SMP_CREDENTIAL MODIFY (
    CREDENTIAL_ACTIVE NUMBER(1,0) CHECK (CREDENTIAL_ACTIVE IN (0,1)),
    CREDENTIAL_TARGET VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TARGET IN ('UI','REST_API')),
    CREDENTIAL_TYPE VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TYPE IN ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','CAS'))
    );

ALTER TABLE SMP_CREDENTIAL_AUD MODIFY (
    CREDENTIAL_ACTIVE NUMBER(1,0) CHECK (CREDENTIAL_ACTIVE IN (0,1)),
    CREDENTIAL_TARGET VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TARGET IN ('UI','REST_API')),
    CREDENTIAL_TYPE VARCHAR2(255 CHAR) CHECK (CREDENTIAL_TYPE IN ('USERNAME_PASSWORD','ACCESS_TOKEN','CERTIFICATE','CAS'))
    );

ALTER TABLE SMP_DOCUMENT_PROPERTY MODIFY (
    PROPERTY_TYPE VARCHAR2(64 CHAR) CHECK (PROPERTY_TYPE IN ('STRING','DATETIME','LIST_STRING','MAP_STRING','INTEGER','BOOLEAN','REGEXP','CRON_EXPRESSION','EMAIL','FILENAME','PATH','URL','CERTIFICATE'))
    );

ALTER TABLE SMP_DOCUMENT_PROPERTY_AUD MODIFY (
    PROPERTY_TYPE VARCHAR2(64 CHAR) CHECK (PROPERTY_TYPE IN ('STRING','DATETIME','LIST_STRING','MAP_STRING','INTEGER','BOOLEAN','REGEXP','CRON_EXPRESSION','EMAIL','FILENAME','PATH','URL','CERTIFICATE'))
    );

ALTER TABLE SMP_DOCUMENT_VERSION MODIFY (
    STATUS VARCHAR2(255 CHAR) CHECK (STATUS IN ('DRAFT','PUBLISHED','RETIRED','UNDER_REVIEW','APPROVED','REJECTED'))
    );

ALTER TABLE SMP_DOCUMENT_VERSION_AUD MODIFY (
    STATUS VARCHAR2(255 CHAR) CHECK (STATUS IN ('DRAFT','PUBLISHED','RETIRED','UNDER_REVIEW','APPROVED','REJECTED'))
    );

ALTER TABLE SMP_DOCUMENT_VERSION_EVENT MODIFY (
    EVENT_SOURCE VARCHAR2(255 CHAR) CHECK (EVENT_SOURCE IN ('UI','REST_API','CRON','PLUGIN','OTHER')),
    EVENT_TYPE VARCHAR2(255 CHAR) CHECK (EVENT_TYPE IN ('CREATE','UPDATE','PUBLISH','REQUEST_REVIEW','RETIRE','APPROVE','REJECT','ERROR','SETTINGS_CHANGE')),
    EVENT_STATUS VARCHAR2(255 CHAR) CHECK (EVENT_STATUS IN ('DRAFT','PUBLISHED','RETIRED','UNDER_REVIEW','APPROVED','REJECTED'))
    );

ALTER TABLE SMP_DOMAIN MODIFY (
    VISIBILITY VARCHAR2(64 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE')),
    SML_CLIENT_CERT_AUTH NUMBER(1,0) CHECK (SML_CLIENT_CERT_AUTH IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_AUD MODIFY (
    VISIBILITY VARCHAR2(64 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE')),
    SML_CLIENT_CERT_AUTH NUMBER(1,0) CHECK (SML_CLIENT_CERT_AUTH IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_CONFIGURATION MODIFY (
    SYSTEM_DEFAULT NUMBER(1,0) CHECK (SYSTEM_DEFAULT IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_CONFIGURATION_AUD MODIFY (
    SYSTEM_DEFAULT NUMBER(1,0) CHECK (SYSTEM_DEFAULT IN (0,1))
    );

ALTER TABLE SMP_DOMAIN_MEMBER MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_DOMAIN_MEMBER_AUD MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_GROUP MODIFY (
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_GROUP_AUD MODIFY (
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_GROUP_MEMBER MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_GROUP_MEMBER_AUD MODIFY (
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_RESOURCE MODIFY (
    REVIEW_ENABLED NUMBER(1,0) CHECK (REVIEW_ENABLED IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1)),
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_RESOURCE_AUD MODIFY (
    REVIEW_ENABLED NUMBER(1,0) CHECK (REVIEW_ENABLED IN (0,1)),
    SML_REGISTERED NUMBER(1,0) CHECK (SML_REGISTERED IN (0,1)),
    VISIBILITY VARCHAR2(128 CHAR) CHECK (VISIBILITY IN ('PUBLIC','INTERNAL','PRIVATE'))
    );

ALTER TABLE SMP_RESOURCE_MEMBER MODIFY (
    PERMISSION_REVIEW NUMBER(1,0) CHECK (PERMISSION_REVIEW IN (0,1)),
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_RESOURCE_MEMBER_AUD MODIFY (
    PERMISSION_REVIEW NUMBER(1,0) CHECK (PERMISSION_REVIEW IN (0,1)),
    MEMBERSHIP_ROLE VARCHAR2(64 CHAR) CHECK (MEMBERSHIP_ROLE IN ('VIEWER','ADMIN'))
    );

ALTER TABLE SMP_RESOURCE_DEF ADD (
    URL_SEGMENT_OPTIONAL VARCHAR2(128 CHAR) UNIQUE
    );

ALTER TABLE SMP_RESOURCE_DEF_AUD ADD (
    URL_SEGMENT_OPTIONAL VARCHAR2(128 CHAR)
    );

ALTER TABLE SMP_SUBRESOURCE_DEF ADD (
    URL_SEGMENT_OPTIONAL VARCHAR2(128 CHAR) UNIQUE
    );

ALTER TABLE SMP_SUBRESOURCE_DEF_AUD ADD (
    URL_SEGMENT_OPTIONAL VARCHAR2(128 CHAR)
    );

ALTER TABLE SMP_USER MODIFY (
    ACTIVE NUMBER(1,0) CHECK (ACTIVE IN (0,1)),
    APPLICATION_ROLE VARCHAR2(256 CHAR) CHECK (APPLICATION_ROLE IN ('USER','SYSTEM_ADMIN'))
    );

ALTER TABLE SMP_USER_AUD MODIFY (
    ACTIVE NUMBER(1,0) CHECK (ACTIVE IN (0,1)),
    APPLICATION_ROLE VARCHAR2(256 CHAR) CHECK (APPLICATION_ROLE IN ('USER','SYSTEM_ADMIN'))
    );

-- 6. Add/replace UNIQUE constraints (if not already present)

-- Step 1: Drop the existing unique constraint
ALTER TABLE SMP_CERTIFICATE DROP CONSTRAINT UK_3x3rvf6hkim9fg16caurkgg6f;
ALTER TABLE SMP_EXTENSION DROP CONSTRAINT UK_p4vfhgs7fvuo6uebjsuqxrglg;
ALTER TABLE SMP_RESOURCE_DEF DROP CONSTRAINT UK_k7l5fili2mmhgslv77afg4myo;
ALTER TABLE SMP_RESOURCE_DEF DROP CONSTRAINT UK_jjbctkhd4h0u9whb1i9wbxwoe;
ALTER TABLE SMP_SUBRESOURCE_DEF DROP CONSTRAINT UK_pmdcnfwm5in2q9ky0b6dlgqvi;
ALTER TABLE SMP_USER DROP CONSTRAINT UK_rt1f0anklfo05lt0my05fqq6;


-- Step 2: Modify the column to include inline UNIQUE constraint
ALTER TABLE SMP_CERTIFICATE MODIFY CERTIFICATE_ID VARCHAR2(1024 CHAR) UNIQUE;
ALTER TABLE SMP_EXTENSION MODIFY IDENTIFIER varchar2(128 char) unique;
ALTER TABLE SMP_RESOURCE_DEF MODIFY IDENTIFIER varchar2(128 char) unique;
ALTER TABLE SMP_RESOURCE_DEF MODIFY URL_SEGMENT varchar2(128 char) unique;
ALTER TABLE SMP_SUBRESOURCE_DEF MODIFY IDENTIFIER varchar2(128 char) unique;
ALTER TABLE SMP_USER MODIFY USERNAME varchar2(64 char) unique;


-- 8. Add new foreign keys

ALTER TABLE SMP_DOCUMENT_CERTIFICATE
    ADD CONSTRAINT FKdo996u5n5vqp9950jbrd32tpv FOREIGN KEY (ID) REFERENCES SMP_DOCUMENT_PROPERTY;

ALTER TABLE SMP_DOCUMENT_CERTIFICATE_AUD
    ADD CONSTRAINT FKlfwn1ehct3domxnwc1dr3mx4g FOREIGN KEY (REV) REFERENCES SMP_REV_INFO;

ALTER TABLE SMP_DOMAIN_DOC_TMPL
    ADD CONSTRAINT FKg4ci2nee5nvm2tbdbpkeom53m FOREIGN KEY (FK_DOCUMENT_ID) REFERENCES SMP_DOCUMENT;
ALTER TABLE SMP_DOMAIN_DOC_TMPL
    ADD CONSTRAINT FK8dwm6w0x0rdiouvt74i07s9u5 FOREIGN KEY (FK_DOREDEF_ID) REFERENCES SMP_DOMAIN_RESOURCE_DEF;
ALTER TABLE SMP_DOMAIN_DOC_TMPL
    ADD CONSTRAINT FK45eaf7nmo1dem40af2dw27jh5 FOREIGN KEY (FK_SUREDEF_ID) REFERENCES SMP_SUBRESOURCE_DEF;

ALTER TABLE SMP_DOMAIN_DOC_TMPL_AUD
    ADD CONSTRAINT FKb1dw4r0rpj3jdtff4jc7gn046 FOREIGN KEY (REV) REFERENCES SMP_REV_INFO;

ALTER TABLE SMP_PERIODICAL_ALERT_AUD
    ADD CONSTRAINT FK7qyb720heygkwc5mmpaer2iou FOREIGN KEY (REV) REFERENCES SMP_REV_INFO;

-- END OF UPGRADE SCRIPT