ALTER TABLE SMP_CERTIFICATE ADD CRL_URL varchar(4000);
ALTER TABLE SMP_CERTIFICATE_AUD ADD CRL_URL varchar(4000);

ALTER TABLE SMP_CERTIFICATE ADD PEM_ENCODED_CERT longtext;
ALTER TABLE SMP_CERTIFICATE_AUD ADD PEM_ENCODED_CERT longtext;
