ALTER TABLE SMP_CERTIFICATE ADD  CRL_URL varchar2(4000 char);
ALTER TABLE SMP_CERTIFICATE_AUD ADD  CRL_URL varchar2(4000 char);

ALTER TABLE SMP_CERTIFICATE ADD  PEM_ENCODED_CERT clob;
ALTER TABLE SMP_CERTIFICATE_AUD ADD  PEM_ENCODED_CERT clob;


