export enum PropertyValueTypeEnum {
  STRING = 'STRING',
  CRON_EXPRESSION = 'CRON_EXPRESSION',
  //LIST_STRING = 'LIST_STRING',
  //MAP_STRING = 'MAP_STRING',
  //FILENAME = 'FILENAME',
  //PATH = 'PATH',
  INTEGER = 'INTEGER',
  BOOLEAN = 'BOOLEAN',
  REGEXP = 'REGEXP',
  EMAIL = 'EMAIL',
  URL = 'URL',
  CERTIFICATE = 'CERTIFICATE',
}
