--------------------------------------------------------
--DELETE FROM SMP_CONFIGURATION_AUD;
DELETE FROM SMP_OWNERSHIP_AUD;
DELETE FROM SMP_SERVICE_METADATA_XML_AUD;
DELETE FROM SMP_SERVICE_METADATA_AUD;
DELETE FROM SMP_SG_EXTENSION_AUD;
DELETE FROM SMP_SERVICE_GROUP_DOMAIN_AUD;
DELETE FROM SMP_SERVICE_GROUP_AUD ;
DELETE FROM SMP_DOMAIN_AUD;
DELETE FROM SMP_CERTIFICATE_AUD ;
DELETE FROM SMP_USER_AUD;
DELETE FROM SMP_REV_INFO;


DELETE FROM SMP_CONFIGURATION;
DELETE FROM SMP_OWNERSHIP;
DELETE FROM SMP_SERVICE_METADATA_XML;
DELETE FROM SMP_SERVICE_METADATA;
DELETE FROM SMP_SG_EXTENSION;
DELETE FROM SMP_SERVICE_GROUP_DOMAIN;
DELETE FROM SMP_SERVICE_GROUP;
DELETE FROM SMP_DOMAIN;
DELETE FROM SMP_CERTIFICATE;
DELETE FROM SMP_USER;
DELETE FROM SMP_OWNERSHIP;




