--------------------------------------------------------
--  File created - Thursday-August-30-2018   
--------------------------------------------------------
/*

Insert into SMP_DOMAIN (DOMAINID,BDMSLCLIENTCERTHEADER,BDMSLCLIENTCERTALIAS,BDMSLSMPID,SIGNATURECERTALIAS) values ('peppol','sno=3b3b162e7d37dd2e50edc6d3378997e1&subject=CN=SMP_OpenPEPPOL SMK 003,O=OpenPEPPOL,C=BE&validfrom=Oct 12 10:37:53 2016 CEST&validto=Oct 1 10:37:53 2018 CEST&issuer=CN=PEPPOL Root TEST CA,OU=FOR TEST PURPOSES ONLY,O=NATIONAL IT AND TELECOM AGENCY,C=DK',null,'CEF-TEST-PEPPOL-SMP',null);
Insert into SMP_DOMAIN (DOMAINID,BDMSLCLIENTCERTHEADER,BDMSLCLIENTCERTALIAS,BDMSLSMPID,SIGNATURECERTALIAS) values ('default','sno=3b3b162e7d37dd2e50edc6d3378997e1&subject=CN=SMP_OpenPEPPOL SMK 003,O=OpenPEPPOL,C=BE&validfrom=Oct 12 10:37:53 2016 CEST&validto=Oct 1 10:37:53 2018 CEST&issuer=CN=PEPPOL Root TEST CA,OU=FOR TEST PURPOSES ONLY,O=NATIONAL IT AND TELECOM AGENCY,C=DK',null,'DEFAULT-SMP-ID',null);


Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('AdminSMP1TEST','0007:001:oasis','iso6523-actorid-upis');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('AdminSMP1TEST','0007:002:oasis','iso6523-actorid-upis');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('AdminSMP1TEST','00117770010100777','urn:oasis:names:tc:ebcore:partyid-type:iso6523:0088');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('AdminSMP1TEST','0077:7777717777777difi','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('AdminSMP1TEST','0077:RP:TEST','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('AdminSMP1TEST','0088:7770010100777','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_AP_TEST_00000,O=European Commission,C=BE:23b207cb468b8519','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_EC,O=European Commission,C=BE:f71ee8b11cb3b787','0007:9340033829dev01','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_EC,O=European Commission,C=BE:f71ee8b11cb3b787','0007:9340033829dev02','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_EC,O=European Commission,C=BE:f71ee8b11cb3b787','0007:9340033829dev1','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_EC,O=European Commission,C=BE:f71ee8b11cb3b787','0007:9340033829test2','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_EC,O=European Commission,C=BE:f71ee8b11cb3b787','0088:777ehealth10100777','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_TEST_BRAZIL,O=European Commission,C=BE:0000000000000123','urn:cipa:ncpb','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=EHEALTH_SMP_TEST_BRAZIL,O=European Commission,C=BE:48b681ee8e0dcc08','0088:5798000000120','iso6523-actorid-upis');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=GENERALERDS_AP_TEST_00000,O=European Commission,C=BE:e6588be5c376f78e','0088:123456','iso6523-actorid-upis');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=GENERALERDS_AP_TEST_00000,O=European Commission,C=BE:e6588be5c376f78e','0088:1234567','iso6523-actorid-upis');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=GENERALERDS_AP_TEST_00000,O=European Commission,C=BE:e6588be5c376f78e','0088:918247451','iso6523-actorid-upis');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=SMP_CONNECTIVITYTEST_05,O=Connectivity Test,C=BE:0000000000001052','0007:9340033829:jrc:02','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=SMP_OpenPEPPOL SMK 003,O=OpenPEPPOL,C=BE:3b3b162e7d37dd2e50edc6d3378997e1','0007:9340033829:jrc','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=SMP_OpenPEPPOL SMK 003,O=OpenPEPPOL,C=BE:3b3b162e7d37dd2e50edc6d3378997e1','0007:9340033829:jrc:01','ehealth-actorid-qns');
Insert into SMP_OWNERSHIP (USERNAME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME) values ('CN=SMP_OpenPEPPOL SMK 003,O=OpenPEPPOL,C=BE:3b3b162e7d37dd2e50edc6d3378997e1','0007:9340033829dev03','ehealth-actorid-qns');


Insert into SMP_PROCESS (DOCUMENTIDENTIFIERSCHEME,PROCESSIDENTIFIER,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER,PROCESSIDENTIFIERTYPE) values ('busdox-docid-qns','urn:www.cenbii.eu:profile:bii04:ver1.0','0088:5798000000112','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:Invoice-12::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:#urn:www.peppol.eu:bis:peppol4a:ver1.0::2.0','cenbii-procid-ubl');
Insert into SMP_PROCESS (DOCUMENTIDENTIFIERSCHEME,PROCESSIDENTIFIER,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER,PROCESSIDENTIFIERTYPE) values ('busdox-docid-qns','urn:www.cenbii.eu:profile:bii05:ver2.0','0007:9340033829test','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2::CreditNote##urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1','cenbii-procid-ubl');
Insert into SMP_PROCESS (DOCUMENTIDENTIFIERSCHEME,PROCESSIDENTIFIER,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER,PROCESSIDENTIFIERTYPE) values ('busdox-docid-qns','urn:www.cenbii.eu:profile:bii05:ver2.0','0007:9340033829test','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1','cenbii-procid-ubl');
Insert into SMP_PROCESS (DOCUMENTIDENTIFIERSCHEME,PROCESSIDENTIFIER,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER,PROCESSIDENTIFIERTYPE) values ('ehealth-resid-qns','urn:www.cenbii.eu:profile:bii04:ver1.0','0002:gutek','iso6523-actorid-upis','urn::epsos##services:extended:epsos::51','cenbii-procid-ubl');
Insert into SMP_PROCESS (DOCUMENTIDENTIFIERSCHEME,PROCESSIDENTIFIER,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER,PROCESSIDENTIFIERTYPE) values ('ehealth-resid-qns','urn:www.cenbii.eu:profile:bii04:ver1.0','0002:gutek','iso6523-actorid-upis','urn::epsos##services:extended:epsos::52','cenbii-procid-ubl');

Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:5798000000113','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:aaaa:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:5798000000112','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:5798700000112','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:002:oasis','iso6523-actorid-upis','peppol');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:1238000000666','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:123456','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0002:gutek','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:918247451','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('00117770010100777','urn:oasis:names:tc:ebcore:partyid-type:iso6523:0088','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:5798000000120','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:aaa:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:bbb:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0077:7777717777777difi','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:777ehealth10100777','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:ehealth:eu:ncp-idp','ehealth-participantid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829test2','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:1234567','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829dev1','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0088:7770010100777','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:ro:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('ro','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('ro-0001','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('ro-0002','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('it-0001','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('it-0002','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('bg-l001','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('bg-l002','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('it-l001','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('bg-lx001','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('bg-xx123','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('it-lx001','participant-demo-scheme','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0077:RP:TEST','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829dev01','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829dev02','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829dev03','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829:jrc:02','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829test','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:cipa:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:romania:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829:jrc','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829:jrc:01','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:9340033829testsupport','iso6523-actorid-upis','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('urn:poland:ncpb','ehealth-actorid-qns','default');
Insert into SMP_SERVICE_GROUP (BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOMAINID) values ('0007:001:oasis','iso6523-actorid-upis','peppol');


Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:001:oasis','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:creditnote-2::creditnote##urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:002:oasis','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:creditnote-2::creditnote##urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:9340033829dev1','ehealth-actorid-qns','urn:oasis:names:specification:ubl:schema:xsd:invoice-2::invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.2');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:9340033829test','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2::CreditNote##urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:9340033829test','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:9340033829test2','ehealth-actorid-qns','urn:oasis:names:specification:ubl:schema:xsd:creditnote-2::creditnote##urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:9340033829test2','ehealth-actorid-qns','urn:oasis:names:specification:ubl:schema:xsd:invoice-2::invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0007:9340033829testsupport','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:Invoice-12::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:#urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('busdox-docid-qns','0088:5798000000112','iso6523-actorid-upis','urn:oasis:names:specification:ubl:schema:xsd:Invoice-12::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:#urn:www.peppol.eu:bis:peppol4a:ver1.0::2.0');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-l001','participant-demo-scheme','agrex');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-l001','participant-demo-scheme','agrim');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-l002','participant-demo-scheme','agrex');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-l002','participant-demo-scheme','agrim');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-lx001','participant-demo-scheme','agrex');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-lx001','participant-demo-scheme','agrim');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-xx123','participant-demo-scheme','agrex');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','bg-xx123','participant-demo-scheme','agrim');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-0001','participant-demo-scheme','agrex-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-0001','participant-demo-scheme','agrim-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-0002','participant-demo-scheme','agrex-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-0002','participant-demo-scheme','agrim-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-l001','participant-demo-scheme','agrex');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-l001','participant-demo-scheme','agrim');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-lx001','participant-demo-scheme','agrex');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','it-lx001','participant-demo-scheme','agrim');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','ro-0001','participant-demo-scheme','agrex-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','ro-0001','participant-demo-scheme','agrim-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','ro-0002','participant-demo-scheme','agrex-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('document-demo-scheme','ro-0002','participant-demo-scheme','agrim-request');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','0002:gutek','iso6523-actorid-upis','urn::epsos##services:extended:epsos::51');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','0002:gutek','iso6523-actorid-upis','urn::epsos##services:extended:epsos::52');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:aaa:ncpb','ehealth-actorid-qns','urn::epsos##services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:cipa:ncpb','ehealth-actorid-qns','urn::epsos##services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:eu:ncp-idp','ehealth-participantid-qns','urn:ehealth:ism::internationalsearchmask##ehealth-107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:CountryBIdentityProvider::XUA::ProvideX-UserAssertion##ITI-40');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:ISM::InternationalSearchMask##ehealth-107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:PatientIdentificationAndAuthentication::XCPD::CrossGatewayPatientDiscovery##ITI-55');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:ProvisioningOfData:BPPC-RegisterUpdate::XDR::ProvideandRegisterDocumentSet-b##ITI-41');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:ProvisioningOfData:Provide::XDR::ProvideandRegisterDocumentSet-b##ITI-41');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:RequestOfData::XCA::CrossGatewayQuery##ITI-38');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:VPN::VPNGatewayServer##ehealth-105');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:countrybidentityprovider::identityprovider::hpauthentication##epsos-91');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:ism::internationalsearchmask##ehealth-107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:patientidentificationandauthentication::xcpd::crossgatewaypatientdiscovery##iti-55');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:provisioningofdata:bppc-registerupdate::xdr::provideandregisterdocumentset-b##iti-41');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:provisioningofdata:provide::xdr::provideandregisterdocumentset-b##iti-41');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:requestofdata::xca::crossgatewayquery##iti-38');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:requestofdata::xca::crossgatewayretrieve##iti-39');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:requestofdata::xcf::crossgatewayfetchrequest##iti-63');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:vpn::vpngatewayclient##ehealth-106');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ehealth:pt:ncpb-idp','ehealth-participantid-qns','urn:ehealth:vpn::vpngatewayserver##ehealth-105');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:poland:ncpb','ehealth-actorid-qns','urn::epsos##services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:poland:ncpb','ehealth-actorid-qns','utf-8');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:ro:ncpb','ehealth-actorid-qns','urn::epsos##services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('ehealth-resid-qns','urn:romania:ncpb','ehealth-actorid-qns','urn::epsos##services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('iso6523-actorid-upis','0088:123456','iso6523-actorid-upis','services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('iso6523-actorid-upis','0088:5798000000120','iso6523-actorid-upis','services:extended:epsos::107');
Insert into SMP_SERVICE_METADATA (DOCUMENTIDENTIFIERSCHEME,BUSINESSIDENTIFIER,BUSINESSIDENTIFIERSCHEME,DOCUMENTIDENTIFIER) values ('iso6523-actorid-upis','0088:918247451','iso6523-actorid-upis','services:extended:epsos::107');


Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('test','$2a$10$fvONLZ1J80Sj.4C2w0/UBuYxHEGoXLIZgZfxqEXoDSH8q3fbTcGJ6',0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=GENERALERDS_AP_TEST_00000,O=European Commission,C=BE:e6588be5c376f78e',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=GENERALERDS_AP_TEST_00000/serialNumber\=1,O=European Commission,C=BE:e6588be5c376f78e',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('smp_admin','$2a$10$.iCtVZuxZM1l4MwNZ7P9..DfwTOplrq8OeynghNiHNE.LIP.UmF42',1);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=EHEALTH_SMP_TEST_BRAZIL,O=European Commission,C=BE:48b681ee8e0dcc08',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=EHEALTH_SMP_EC_PassedDate,O=European Commission,C=BE:00000000589C4C3B',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=EHEALTH_SMP_EC,O=European Commission,C=BE:f71ee8b11cb3b787',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=EHEALTH_AP_TEST_00000/serialNumber\=1,O=European Commission,C=BE:23b207cb468b8519',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=EHEALTH_AP_TEST_00000,O=European Commission,C=BE:23b207cb468b8519',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('AdminSMP1TEST','$2a$10$vrTybiXuFJiGaCJksihuNeaLZnAKwjIcL7KYopxFyZdoRlzs9qZCm',1);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('AdminSMP2TEST','$2a$10$OIRWlcLV7TXEoWr9SsxLk..vpHhNPDmBPxUjgCL/euNVHxhvtnhBi',1);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=GRP:SMP_TEST_\+\,& \=eau/emailAddress\=CEF-EDELIVERY-SUPPORT@ec.europa.eu/serialNumber\=1,O=European Commission,C=BE:6eef83f5ef06a05b',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=SMP_OpenPEPPOL SMK 003,O=OpenPEPPOL,C=BE:3b3b162e7d37dd2e50edc6d3378997e1',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=SMP_CONNECTIVITYTEST_05,O=Connectivity Test,C=BE:0000000000001052',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=SMP_CONNECTIVITYTEST_05/emailAddress/=CEF-EDELIVERY-SUPPORT@ec.europa.eu,O=Connectivity Test,C=BE:0000000000001052',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=EHEALTH_SMP_TEST_BRAZIL,O=European Commission,C=BE:0000000000000123',null,0);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('CN=slash/backslash\\quote\"colon:_rfc2253special_ampersand&comma\,equals\=plus\+lessthan\<greaterthan\>hash\#semicolon\;end,O=DEáºžÃŸÃ„Ã¤PLÅ¼Ã³Å‚Ä‡NOÃ†Ã¦Ã˜Ã¸Ã…Ã¥,C=PL:0000000000001010',null,1);
Insert into SMP_USER (USERNAME,PASSWORD,ISADMIN) values ('admin','$2a$10$jsZamGH2qv8SVnRy55bKOOXof0QbIOaOqsYT/Ujo2Eb7dVQxG0Hd6',0);
*/