<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ec.europa.eu/digit/domibus/wsdl/endpoint/basic" xmlns:dac="http://ec.europa.eu/digit/domibus/common/aggregate/components" targetNamespace="http://ec.europa.eu/digit/domibus/wsdl/endpoint/basic">
	<wsdl:types>
		<xsd:schema xmlns="http://ec.europa.eu/digit/domibus/wsdl/endpoint/basic" targetNamespace="http://ec.europa.eu/digit/domibus/wsdl/endpoint/basic" elementFormDefault="qualified">
			<xsd:import namespace="http://ec.europa.eu/digit/domibus/common/aggregate/components" schemaLocation="../xsd/DMS-AggregateComponents-0.01.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Envelope">
		<wsdl:part name="GatewayHeader" element="dac:GatewayHeader"/>
		<wsdl:part name="GatewayBody" element="dac:GatewayBody"/>
	</wsdl:message>
	<wsdl:message name="Acknowledgement">
		<wsdl:part name="Acknowledgement" element="dac:Acknowledgement"/>
	</wsdl:message>
	<wsdl:message name="FaultResponse">
		<wsdl:part name="FaultResonse" element="dac:FaultDetail"/>
	</wsdl:message>
	<wsdl:portType name="DomibusBasicInterface">
		<wsdl:operation name="submit">
			<wsdl:input message="tns:Envelope"/>
			<wsdl:output message="tns:Acknowledgement"/>
			<wsdl:fault name="FaultResponse" message="tns:FaultResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="DomibusBasicInterfaceSoapBinding" type="tns:DomibusBasicInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="submit">
			<soap:operation soapAction=""/>
			<wsdl:input>
				<soap:header message="tns:Envelope" part="GatewayHeader" use="literal"/>
				<soap:body parts="GatewayBody" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="FaultResponse">
				<soap:fault name="FaultResponse" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DomibusBasicService">
		<wsdl:port name="DomibusBasicBinding" binding="tns:DomibusBasicInterfaceSoapBinding">
			<soap:address location="/services/basic/domibus-basic-endpoint"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
