package eu.europa.ec.cipa.transport.start.client.console;

import org.apache.commons.cli.Options;

public final class StartClientOptions extends Options {

	public StartClientOptions() {
		super();
		addOption("m", "clientmode", true, "The client console mode : \n DIRECT_AP : Sends the document directly to the Access point without using sml and smp (requires ap url)" +
				  "\n DIRECT_SMP : Sends the document querying the provided smp url to get the recipient endpoint(requires ap url)" +
				  "\n FULL : Sends the document using the full transport infrastructure");
		addOption("ap", "apurl", true, "URL of the recipient access point  in case of DIRECT_AP client mode");
		addOption("smp", "smpurl", true, "URL of smp to use in case of DIRECT_SMP client mofde");
		addOption("s", "senderid", true, "Business id of the sender fi 0088:123456789");
		addOption("r", "recipientid", true, "Business id of the recipient fi  0088:123456710");
		addOption("p", "processid", true, "Process id to perform operation on ");
		addOption("d", "documenttypeId", true,"Document id to perform operation on");
		addOption("dpath", "documentPath", true,"the path pointing to the xml file to send");
		addOption("muid", "messageID", true,"Optional Message Identifier if not present uid gets generated by the ap");
		addOption("ping", "sendPingMessage",true,"Optional : set this value to true if you want to send a ping message");
		addOption("debug", "enableDebug",true,"Optional : set this value to true if you want to enable metro debug");
		addOption("proxy","useProxt",true,"Optional : set this value to true if you want to use proxy edit the configProxy.properties file under the conf folder "); 
	}

}
