package ddsl.enums;

public enum Pages {
    SEARCH_RESOURCES,
    ADMINISTRATION_EDIT_DOMAINS,
    ADMINISTRATION_EDIT_GROUPS,
    ADMINISTRATION_EDIT_RESOURCES,
    SYSTEM_SETTINGS_USERS,
    SYSTEM_SETTINGS_DOMAINS,
    SYSTEM_SETTINGS_KEYSTORE,
    SYSTEM_SETTINGS_TRUSTSTORE,
    SYSTEM_SETTINGS_EXTENSIONS,
    SYSTEM_SETTINGS_PROPERTIES,
    SYSTEM_SETTINGS_ALERS,
    USER_SETTINGS_PROFILE,
    USER_SETTINGS_ACCESS_TOKEN,
    USER_SETTINGS_CERTIFICATES
}
