ALTER TABLE smp_endpoint DROP CONSTRAINT smpndpintdcmntIdentifierScheme
ALTER TABLE smp_ownership DROP CONSTRAINT smpownershipbusinessIdentifier
ALTER TABLE smp_ownership DROP CONSTRAINT FK_smp_ownership_username
ALTER TABLE smp_process DROP CONSTRAINT smpprcessdcmntIdentifierScheme
ALTER TABLE smp_service_metadata DROP CONSTRAINT smpsrvcemetadatabsnssdentifier
DROP TABLE smp_endpoint CASCADE CONSTRAINTS
DROP TABLE smp_ownership CASCADE CONSTRAINTS
DROP TABLE smp_process CASCADE CONSTRAINTS
DROP TABLE smp_service_group CASCADE CONSTRAINTS
DROP TABLE smp_service_metadata CASCADE CONSTRAINTS
DROP TABLE smp_user CASCADE CONSTRAINTS
DROP TABLE smp_service_metadata_red CASCADE CONSTRAINTS
