/*
 * Copyright 2017 European Commission | CEF eDelivery
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 * or file: LICENCE-EUPL-v1.1.pdf
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */

/*
 * Copyright 2017 European Commission | CEF eDelivery
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 * or file: LICENCE-EUPL-v1.1.pdf
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */
package eu.europa.ec.edelivery.smp.data.model;

import javax.annotation.Nullable;
import javax.persistence.*;
import java.io.Serializable;

/**
 * ServiceMetadata generated by hbm2java
 * 
 * @author PEPPOL.AT, BRZ, Philip Helger
 */
@Entity
@Table (name = "smp_service_metadata")
public class DBServiceMetadata implements Serializable {

  private DBServiceMetadataID m_aID;
  private DBServiceGroup m_aServiceGroup;
  private String m_sExtension;
  private String m_sXmlContent;

  public DBServiceMetadata () {}

  public DBServiceMetadata (final DBServiceMetadataID aID, final DBServiceGroup aServiceGroup) {
    m_aID = aID;
    m_aServiceGroup = aServiceGroup;
  }

  public DBServiceMetadata (final DBServiceMetadataID aID,
                            final DBServiceGroup aServiceGroup,
                            final String sExtension,
                            final String sXmlContent) {
    m_aID = aID;
    m_aServiceGroup = aServiceGroup;
    m_sExtension = sExtension;
    m_sXmlContent = sXmlContent;
  }

  @EmbeddedId
  public DBServiceMetadataID getId () {
    return m_aID;
  }

  public void setId (final DBServiceMetadataID aID) {
    m_aID = aID;
  }

  @ManyToOne (fetch = FetchType.LAZY)
  @JoinColumns ({ @JoinColumn (name = "businessIdentifier",
                               referencedColumnName = "businessIdentifier",
                               nullable = false,
                               insertable = false,
                               updatable = false),
                 @JoinColumn (name = "businessIdentifierScheme",
                              referencedColumnName = "businessIdentifierScheme",
                              nullable = false,
                              insertable = false,
                              updatable = false) })
  public DBServiceGroup getServiceGroup () {
    return m_aServiceGroup;
  }

  public void setServiceGroup (final DBServiceGroup aServiceGroup) {
    m_aServiceGroup = aServiceGroup;
  }

  @Lob
  @Column(name = "xmlcontent")
  public String getXmlContent(){
    return m_sXmlContent;
  }

  public void setXmlContent(String sXmlContent){
    m_sXmlContent = sXmlContent;
  }

}
