@echo off
rem usage: StartClientConsole
rem  -ap,--apurl <arg>               URL of the recipient access point  in
rem                                  case of DIRECT_AP client mode
rem  -d,--documenttypeId <arg>       Document id to perform operation on
rem  -dpath,--documentPath <arg>     the path pointing to the xml file to send
rem  -m,--clientmode <arg>           The client console mode :
rem                                 DIRECT_AP : Sends the document directly
rem                                  to the Access point without using sml and
rem                                  smp (requires ap url)
rem                                  DIRECT_SMP : Sends the document querying
rem                                  the provided smp url to get the recipient
rem                                  endpoint(requires ap url)
rem                                  FULL : Sends the document using the full
rem                                  transport infrastructure
rem  -muid,--messageID <arg>         Optional Message Identifier if not
rem                                  present uid gets generated by the ap
rem  -p,--processid <arg>            Process id to perform operation on
rem  -ping,--sendPingMessage <arg>   Optional : set this value to true if you
rem                                 want to send a ping message
rem  -r,--recipientid <arg>          Business id of the recipient fi
rem                                  0088:123456710
rem  -s,--senderid <arg>             Business id of the sender fi
rem                                  0088:123456789
rem  -smp,--smpurl <arg>             URL of smp to use in case of DIRECT_SMP
 
 java -Djava.endorsed.dirs="${ClientIntallPathHere}\endorsed" -jar cipa-start-client.jar -m DIRECT_AP -s 0088:810017902 -r 0088:123456710 -ap "https://localhost:8443/cipa-start-server/accessPointService" -d "urn_oasis_names_specification_ubl_schema_xsd_Invoice_2__Invoice__urn_www_cenbii_eu_transaction_biicoretrdm010_ver1_0__urn_www_peppol_eu_bis_peppol4a_ver1_0__2_0" -p "urn_www_cenbii_eu_profile_bii04_ver1_0" -dpath "${ClientIntallPathHere}\ehf-test-invoice.xml" 