-- add table column registered to 
ALTER TABLE SMP_DOMAIN ADD SML_REGISTERED bit;
ALTER TABLE SMP_DOMAIN_AUD ADD SML_REGISTERED bit;

ALTER TABLE SMP_DOMAIN ADD SML_BLUE_COAT_AUTH bit;
ALTER TABLE SMP_DOMAIN_AUD ADD SML_BLUE_COAT_AUTH bit;

UPDATE SMP_DOMAIN set SML_REGISTRED=0 where SML_REGISTERED IS NULL;
UPDATE SMP_DOMAIN set SML_BLUE_COAT_AUTH=0 where SML_BLUE_COAT_AUTH IS NULL;


-- fix typo
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN CHANGE COLUMN SML_REGISTRED SML_REGISTERED bit;
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN_AUD CHANGE COLUMN SML_REGISTRED SML_REGISTERED bit;

-- generate configuration table
create table SMP_CONFIGURATION (
   PROPERTY varchar(512)  CHARACTER SET utf8 COLLATE utf8_bin not null,
    CREATED_ON datetime not null,
    DESCRIPTION varchar(4000)  CHARACTER SET utf8 COLLATE utf8_bin,
    LAST_UPDATED_ON datetime not null,
    VALUE varchar(4000)  CHARACTER SET utf8 COLLATE utf8_bin,
    primary key (PROPERTY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
