/*
 * Copyright 2017 European Commission | CEF eDelivery
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 * or file: LICENCE-EUPL-v1.1.pdf
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */
package eu.europa.ec.cipa.smp.server.data.dbms.model;

import javax.annotation.Nullable;
import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceGroup generated by hbm2java
 * 
 * @author PEPPOL.AT, BRZ, Philip Helger
 */
@Entity
@Table (name = "smp_service_group")
public class DBServiceGroup implements Serializable {

  private DBServiceGroupID m_aID;
  private String m_sExtension;
  private Set <DBOwnership> m_aOwnerships = new HashSet <DBOwnership> ();
  private Set <DBServiceMetadata> m_aServiceMetadatas = new HashSet <DBServiceMetadata> ();

  public DBServiceGroup () {}

  public DBServiceGroup (final DBServiceGroupID aID) {
    m_aID = aID;
  }

  public DBServiceGroup (final DBServiceGroupID aID,
                         final String sExtension,
                         final Set <DBOwnership> aOwnerships,
                         final Set <DBServiceMetadata> aServiceMetadatas) {
    m_aID = aID;
    m_sExtension = sExtension;
    m_aOwnerships = aOwnerships;
    m_aServiceMetadatas = aServiceMetadatas;
  }

  @EmbeddedId
  public DBServiceGroupID getId () {
    return m_aID;
  }

  public void setId (final DBServiceGroupID aID) {
    m_aID = aID;
  }

  @Lob
  @Column (name = "extension", length = 65535)
  public String getExtension () {
    return m_sExtension;
  }

  public void setExtension (@Nullable final String sExtension) {
    m_sExtension = sExtension;
  }

  @OneToMany (fetch = FetchType.LAZY, mappedBy = "serviceGroup", cascade = { CascadeType.ALL })
  public Set <DBOwnership> getOwnerships () {
    return m_aOwnerships;
  }

  public void setOwnerships (final Set <DBOwnership> aOwnerships) {
    m_aOwnerships = aOwnerships;
  }

  @OneToMany (fetch = FetchType.LAZY, mappedBy = "serviceGroup", cascade = { CascadeType.ALL })
  public Set <DBServiceMetadata> getServiceMetadatas () {
    return m_aServiceMetadatas;
  }

  public void setServiceMetadatas (final Set <DBServiceMetadata> aServiceMetadatas) {
    m_aServiceMetadatas = aServiceMetadatas;
  }
}
