/*
 * Copyright 2017 European Commission | CEF eDelivery
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 * or file: LICENCE-EUPL-v1.1.pdf
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */
package eu.europa.ec.cipa.smp.server.data.dbms.model;

import javax.persistence.*;
import java.io.Serializable;

/**
 * ServiceMetadataRedirection generated by hbm2java
 * 
 * @author PEPPOL.AT, BRZ, Philip Helger
 */
@Entity
@Table (name = "smp_service_metadata_red")
public class DBServiceMetadataRedirection implements Serializable {

  private DBServiceMetadataRedirectionID m_aID;
  private String m_sRedirectionUrl;
  private String m_sExtension;
  private String m_sCertificateUid;

  public DBServiceMetadataRedirection () {}

  public DBServiceMetadataRedirection (final DBServiceMetadataRedirectionID aID,
                                       final String sRedirectionUrl,
                                       final String sCertificateUid) {
    this (aID, sRedirectionUrl, null, sCertificateUid);
  }

  public DBServiceMetadataRedirection (final DBServiceMetadataRedirectionID aID,
                                       final String sRedirectionUrl,
                                       final String sExtension,
                                       final String sCertificateUid) {
    m_aID = aID;
    m_sRedirectionUrl = sRedirectionUrl;
    m_sExtension = sExtension;
    m_sCertificateUid = sCertificateUid;
  }

  @EmbeddedId
  public DBServiceMetadataRedirectionID getId () {
    return m_aID;
  }

  public void setId (final DBServiceMetadataRedirectionID aID) {
    m_aID = aID;
  }

  @Column (name = "redirectionUrl", nullable = false, length = 256)
  public String getRedirectionUrl () {
    return m_sRedirectionUrl;
  }

  public void setRedirectionUrl (final String sRedirectionUrl) {
    m_sRedirectionUrl = sRedirectionUrl;
  }

  @Lob
  @Column (name = "extension")
  public String getExtension () {
    return m_sExtension;
  }

  public void setExtension (final String sExtension) {
    m_sExtension = sExtension;
  }

  @Column (name = "certificateUID", nullable = false, length = 256)
  public String getCertificateUid () {
    return m_sCertificateUid;
  }

  public void setCertificateUid (final String sCertificateUid) {
    m_sCertificateUid = sCertificateUid;
  }
}
